// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Dynatrace.Outputs
{

    [OutputType]
    public sealed class AppsecNotificationWebhookConfiguration
    {
        public readonly bool AcceptAnyCertificate;
        public readonly Outputs.AppsecNotificationWebhookConfigurationHeaders? Headers;
        public readonly string Url;

        [OutputConstructor]
        private AppsecNotificationWebhookConfiguration(
            bool acceptAnyCertificate,

            Outputs.AppsecNotificationWebhookConfigurationHeaders? headers,

            string url)
        {
            AcceptAnyCertificate = acceptAnyCertificate;
            Headers = headers;
            Url = url;
        }
    }
}
