// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Dynatrace.Outputs
{

    [OutputType]
    public sealed class AppsecNotificationWebhookConfigurationHeadersHeader
    {
        public readonly string Name;
        public readonly bool Secret;
        public readonly string? SecretValue;
        public readonly string? Value;

        [OutputConstructor]
        private AppsecNotificationWebhookConfigurationHeadersHeader(
            string name,

            bool secret,

            string? secretValue,

            string? value)
        {
            Name = name;
            Secret = secret;
            SecretValue = secretValue;
            Value = value;
        }
    }
}
