// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Dynatrace.Outputs
{

    [OutputType]
    public sealed class AppsecNotificationEmailConfiguration
    {
        public readonly ImmutableArray<string> BccRecipients;
        public readonly ImmutableArray<string> CcRecipients;
        public readonly ImmutableArray<string> Recipients;

        [OutputConstructor]
        private AppsecNotificationEmailConfiguration(
            ImmutableArray<string> bccRecipients,

            ImmutableArray<string> ccRecipients,

            ImmutableArray<string> recipients)
        {
            BccRecipients = bccRecipients;
            CcRecipients = ccRecipients;
            Recipients = recipients;
        }
    }
}
