// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Dynatrace.Outputs
{

    [OutputType]
    public sealed class AzureCredentialsSupportingServiceMonitoredMetric
    {
        /// <summary>
        /// a list of metric's dimensions names
        /// </summary>
        public readonly ImmutableArray<string> Dimensions;
        /// <summary>
        /// The name of the tag.
        /// </summary>
        public readonly string? Name;
        /// <summary>
        /// Any attributes that aren't yet supported by this provider
        /// </summary>
        public readonly string? Unknowns;

        [OutputConstructor]
        private AzureCredentialsSupportingServiceMonitoredMetric(
            ImmutableArray<string> dimensions,

            string? name,

            string? unknowns)
        {
            Dimensions = dimensions;
            Name = name;
            Unknowns = unknowns;
        }
    }
}
