// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Dynatrace.Outputs
{

    [OutputType]
    public sealed class BrowserMonitorScriptEventsEventNavigateAuthentication
    {
        /// <summary>
        /// A reference to the entry within the credential vault
        /// </summary>
        public readonly string Creds;
        /// <summary>
        /// The type of the threshold: `TOTAL` (total loading time) or `ACTION` (action loading time)
        /// </summary>
        public readonly string Type;

        [OutputConstructor]
        private BrowserMonitorScriptEventsEventNavigateAuthentication(
            string creds,

            string type)
        {
            Creds = creds;
            Type = type;
        }
    }
}
