// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Dynatrace.Outputs
{

    [OutputType]
    public sealed class BrowserMonitorScriptEventsEventJavascriptTargetLocatorLocator
    {
        /// <summary>
        /// The type of the threshold: `TOTAL` (total loading time) or `ACTION` (action loading time)
        /// </summary>
        public readonly string Type;
        /// <summary>
        /// The value of the cookie. The following symbols are not allowed: `;`, `,`, `\` and `"`.
        /// </summary>
        public readonly string Value;

        [OutputConstructor]
        private BrowserMonitorScriptEventsEventJavascriptTargetLocatorLocator(
            string type,

            string value)
        {
            Type = type;
            Value = value;
        }
    }
}
