// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Dynatrace.Outputs
{

    [OutputType]
    public sealed class BrowserMonitorTagTag
    {
        /// <summary>
        /// The origin of the tag. Supported values are `AWS`, `AWS_GENERIC`, `AZURE`, `CLOUD_FOUNDRY`, `CONTEXTLESS`, `ENVIRONMENT`, `GOOGLE_CLOUD` and `KUBERNETES`.
        /// </summary>
        public readonly string Context;
        public readonly string Key;
        public readonly string? Source;
        /// <summary>
        /// The value of the cookie. The following symbols are not allowed: `;`, `,`, `\` and `"`.
        /// </summary>
        public readonly string? Value;

        [OutputConstructor]
        private BrowserMonitorTagTag(
            string context,

            string key,

            string? source,

            string? value)
        {
            Context = context;
            Key = key;
            Source = source;
            Value = value;
        }
    }
}
