// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Dynatrace.Outputs
{

    [OutputType]
    public sealed class BusinessEventsOneagentTriggersTrigger
    {
        /// <summary>
        /// Case sensitive
        /// </summary>
        public readonly bool? CaseSensitive;
        /// <summary>
        /// Fixed value
        /// </summary>
        public readonly Outputs.BusinessEventsOneagentTriggersTriggerSource Source;
        /// <summary>
        /// Event type
        /// </summary>
        public readonly string Type;
        /// <summary>
        /// no documentation available
        /// </summary>
        public readonly string? Value;

        [OutputConstructor]
        private BusinessEventsOneagentTriggersTrigger(
            bool? caseSensitive,

            Outputs.BusinessEventsOneagentTriggersTriggerSource source,

            string type,

            string? value)
        {
            CaseSensitive = caseSensitive;
            Source = source;
            Type = type;
            Value = value;
        }
    }
}
