// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Dynatrace.Outputs
{

    [OutputType]
    public sealed class CalculatedMobileMetricDimensionDimension
    {
        /// <summary>
        /// A dimensions for the metric usage
        /// </summary>
        public readonly string Dimension;
        /// <summary>
        /// The number of top values to be calculated
        /// </summary>
        public readonly int TopX;

        [OutputConstructor]
        private CalculatedMobileMetricDimensionDimension(
            string dimension,

            int topX)
        {
            Dimension = dimension;
            TopX = topX;
        }
    }
}
