// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Dynatrace.Outputs
{

    [OutputType]
    public sealed class CustomAnomaliesScopeTagFilter
    {
        /// <summary>
        /// The origin of the tag, such as AWS or Cloud Foundry. Custom tags use the `CONTEXTLESS` value
        /// </summary>
        public readonly string Context;
        /// <summary>
        /// The dimensions key on the metric
        /// </summary>
        public readonly string Key;
        /// <summary>
        /// The value to match on
        /// </summary>
        public readonly string? Value;

        [OutputConstructor]
        private CustomAnomaliesScopeTagFilter(
            string context,

            string key,

            string? value)
        {
            Context = context;
            Key = key;
            Value = value;
        }
    }
}
