// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Dynatrace.Outputs
{

    [OutputType]
    public sealed class DataPrivacyMasking
    {
        public readonly string? IpAddressMasking;
        public readonly bool? IpAddressMaskingEnabled;
        public readonly bool PersonalDataUriMaskingEnabled;
        public readonly bool UserActionMaskingEnabled;

        [OutputConstructor]
        private DataPrivacyMasking(
            string? ipAddressMasking,

            bool? ipAddressMaskingEnabled,

            bool personalDataUriMaskingEnabled,

            bool userActionMaskingEnabled)
        {
            IpAddressMasking = ipAddressMasking;
            IpAddressMaskingEnabled = ipAddressMaskingEnabled;
            PersonalDataUriMaskingEnabled = personalDataUriMaskingEnabled;
            UserActionMaskingEnabled = userActionMaskingEnabled;
        }
    }
}
