// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Dynatrace.Outputs
{

    [OutputType]
    public sealed class DataPrivacyDoNotTrack
    {
        public readonly bool ComplyWithDoNotTrack;
        public readonly string? DoNotTrack;

        [OutputConstructor]
        private DataPrivacyDoNotTrack(
            bool complyWithDoNotTrack,

            string? doNotTrack)
        {
            ComplyWithDoNotTrack = complyWithDoNotTrack;
            DoNotTrack = doNotTrack;
        }
    }
}
