// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Dynatrace.Outputs
{

    [OutputType]
    public sealed class EnvironmentStorageLimits
    {
        /// <summary>
        /// Log Monitoring consumption and quota information on environment level. Not set (and not editable) if Log monitoring is not enabled. Not set (and not editable) if Log monitoring is migrated to Davis data on license level
        /// </summary>
        public readonly int? Logs;
        /// <summary>
        /// Session replay storage usage and limit information on environment level in bytes. 0 for unlimited.
        /// </summary>
        public readonly int? SessionReplay;
        /// <summary>
        /// Session replay storage usage and limit information on environment level in bytes. 0 for unlimited.
        /// </summary>
        public readonly int? SymbolFiles;
        /// <summary>
        /// Transaction storage usage and limit information on environment level in bytes. 0 for unlimited.
        /// </summary>
        public readonly int? Transactions;

        [OutputConstructor]
        private EnvironmentStorageLimits(
            int? logs,

            int? sessionReplay,

            int? symbolFiles,

            int? transactions)
        {
            Logs = logs;
            SessionReplay = sessionReplay;
            SymbolFiles = symbolFiles;
            Transactions = transactions;
        }
    }
}
