// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Dynatrace.Outputs
{

    [OutputType]
    public sealed class EnvironmentStorageRetention
    {
        /// <summary>
        /// Log Monitoring consumption and quota information on environment level. Not set (and not editable) if Log monitoring is not enabled. Not set (and not editable) if Log monitoring is migrated to Davis data on license level
        /// </summary>
        public readonly int? Logs;
        /// <summary>
        /// Real user monitoring retention settings on environment level in days. Can be set to any value from 1 to 35 days
        /// </summary>
        public readonly int Rum;
        /// <summary>
        /// Service code level retention settings on environment level in days. Service code level retention time can't be greater than service request level retention time and both can't exceed one year
        /// </summary>
        public readonly int ServiceCodeLevel;
        /// <summary>
        /// Service request level retention settings on environment level in days. Service code level retention time can't be greater than service request level retention time and both can't exceed one year
        /// </summary>
        public readonly int ServiceRequestLevel;
        /// <summary>
        /// Session replay storage usage and limit information on environment level in bytes. 0 for unlimited.
        /// </summary>
        public readonly int SessionReplay;
        /// <summary>
        /// Synthetic monitors consumption and quota information on environment level. Not set (and not editable) if neither Synthetic nor DEM units is enabled
        /// </summary>
        public readonly int Synthetic;

        [OutputConstructor]
        private EnvironmentStorageRetention(
            int? logs,

            int rum,

            int serviceCodeLevel,

            int serviceRequestLevel,

            int sessionReplay,

            int synthetic)
        {
            Logs = logs;
            Rum = rum;
            ServiceCodeLevel = serviceCodeLevel;
            ServiceRequestLevel = serviceRequestLevel;
            SessionReplay = sessionReplay;
            Synthetic = synthetic;
        }
    }
}
