// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Dynatrace.Outputs
{

    [OutputType]
    public sealed class GenericTypesRulesRule
    {
        public readonly Outputs.GenericTypesRulesRuleAttributes? Attributes;
        public readonly string? IconPattern;
        /// <summary>
        /// ID patterns are comprised of static text and placeholders referring to dimensions in the ingest data. An ID pattern **must** contain at least one placeholder to ensure that different entities will be created.. Take care that the pattern results in the same ID for the same entity. For example, using timestamp or counter-like dimensions as part of the ID would lead to the creation of new entities for each ingest data and is strongly discouraged!
        /// </summary>
        public readonly string IdPattern;
        public readonly string? InstanceNamePattern;
        public readonly Outputs.GenericTypesRulesRuleRequiredDimensions? RequiredDimensions;
        public readonly string? Role;
        public readonly Outputs.GenericTypesRulesRuleSources Sources;

        [OutputConstructor]
        private GenericTypesRulesRule(
            Outputs.GenericTypesRulesRuleAttributes? attributes,

            string? iconPattern,

            string idPattern,

            string? instanceNamePattern,

            Outputs.GenericTypesRulesRuleRequiredDimensions? requiredDimensions,

            string? role,

            Outputs.GenericTypesRulesRuleSources sources)
        {
            Attributes = attributes;
            IconPattern = iconPattern;
            IdPattern = idPattern;
            InstanceNamePattern = instanceNamePattern;
            RequiredDimensions = requiredDimensions;
            Role = role;
            Sources = sources;
        }
    }
}
