// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Dynatrace.Outputs
{

    [OutputType]
    public sealed class GetDocumentsValueResult
    {
        public readonly string Id;
        public readonly string Name;
        public readonly string Owner;
        public readonly string Type;

        [OutputConstructor]
        private GetDocumentsValueResult(
            string id,

            string name,

            string owner,

            string type)
        {
            Id = id;
            Name = name;
            Owner = owner;
            Type = type;
        }
    }
}
