// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Dynatrace.Outputs
{

    [OutputType]
    public sealed class GetEntitiesEntityResult
    {
        public readonly string? DisplayName;
        public readonly string? EntityId;
        public readonly int? LastSeenTms;
        public readonly ImmutableDictionary<string, string> Properties;
        public readonly ImmutableArray<Outputs.GetEntitiesEntityTagResult> Tags;
        public readonly string? Type;

        [OutputConstructor]
        private GetEntitiesEntityResult(
            string? displayName,

            string? entityId,

            int? lastSeenTms,

            ImmutableDictionary<string, string> properties,

            ImmutableArray<Outputs.GetEntitiesEntityTagResult> tags,

            string? type)
        {
            DisplayName = displayName;
            EntityId = entityId;
            LastSeenTms = lastSeenTms;
            Properties = properties;
            Tags = tags;
            Type = type;
        }
    }
}
