// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Dynatrace.Outputs
{

    [OutputType]
    public sealed class GetHubItemsItemResult
    {
        public readonly string ActivationLink;
        public readonly string ArtifactId;
        public readonly string AuthorLogo;
        public readonly string AuthorName;
        public readonly bool ClusterCompatible;
        public readonly bool ComingSoon;
        public readonly string Description;
        public readonly string DocumentationLink;
        public readonly bool HasDescriptionBlocks;
        public readonly string ItemId;
        public readonly string Logo;
        public readonly string MarketingLink;
        public readonly string Name;
        public readonly string NotCompatibleReason;
        public readonly ImmutableArray<string> Tags;
        public readonly string Type;

        [OutputConstructor]
        private GetHubItemsItemResult(
            string activationLink,

            string artifactId,

            string authorLogo,

            string authorName,

            bool clusterCompatible,

            bool comingSoon,

            string description,

            string documentationLink,

            bool hasDescriptionBlocks,

            string itemId,

            string logo,

            string marketingLink,

            string name,

            string notCompatibleReason,

            ImmutableArray<string> tags,

            string type)
        {
            ActivationLink = activationLink;
            ArtifactId = artifactId;
            AuthorLogo = authorLogo;
            AuthorName = authorName;
            ClusterCompatible = clusterCompatible;
            ComingSoon = comingSoon;
            Description = description;
            DocumentationLink = documentationLink;
            HasDescriptionBlocks = hasDescriptionBlocks;
            ItemId = itemId;
            Logo = logo;
            MarketingLink = marketingLink;
            Name = name;
            NotCompatibleReason = notCompatibleReason;
            Tags = tags;
            Type = type;
        }
    }
}
