// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Dynatrace.Outputs
{

    [OutputType]
    public sealed class HttpMonitorAnomalyDetectionOutageHandling
    {
        /// <summary>
        /// (Field has overlap with `dynatrace.BrowserMonitorOutage` and `dynatrace.HttpMonitorOutage`) When enabled (`true`), generate a problem and send an alert when the monitor is unavailable at all configured locations
        /// </summary>
        public readonly bool? GlobalOutage;
        /// <summary>
        /// (Field has overlap with `dynatrace.BrowserMonitorOutage` and `dynatrace.HttpMonitorOutage`) Global outage handling configuration.
        /// </summary>
        public readonly ImmutableArray<Outputs.HttpMonitorAnomalyDetectionOutageHandlingGlobalOutagePolicy> GlobalOutagePolicies;
        public readonly bool? LocalOutage;
        public readonly ImmutableArray<Outputs.HttpMonitorAnomalyDetectionOutageHandlingLocalOutagePolicy> LocalOutagePolicies;
        public readonly bool? RetryOnError;

        [OutputConstructor]
        private HttpMonitorAnomalyDetectionOutageHandling(
            bool? globalOutage,

            ImmutableArray<Outputs.HttpMonitorAnomalyDetectionOutageHandlingGlobalOutagePolicy> globalOutagePolicies,

            bool? localOutage,

            ImmutableArray<Outputs.HttpMonitorAnomalyDetectionOutageHandlingLocalOutagePolicy> localOutagePolicies,

            bool? retryOnError)
        {
            GlobalOutage = globalOutage;
            GlobalOutagePolicies = globalOutagePolicies;
            LocalOutage = localOutage;
            LocalOutagePolicies = localOutagePolicies;
            RetryOnError = retryOnError;
        }
    }
}
