// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Dynatrace.Outputs
{

    [OutputType]
    public sealed class HttpMonitorScriptRequestValidationRule
    {
        /// <summary>
        /// The validation condition. `true` means validation succeeds if the specified content/element is found. `false` means validation fails if the specified content/element is found. Always specify `false` for `certificateExpiryDateConstraint` to fail the monitor if SSL certificate expiry is within the specified number of days
        /// </summary>
        public readonly bool? PassIfFound;
        /// <summary>
        /// The type of the threshold: `TOTAL` (total loading time) or `ACTION` (action loading time)
        /// </summary>
        public readonly string Type;
        /// <summary>
        /// The value of the header
        /// </summary>
        public readonly string Value;

        [OutputConstructor]
        private HttpMonitorScriptRequestValidationRule(
            bool? passIfFound,

            string type,

            string value)
        {
            PassIfFound = passIfFound;
            Type = type;
            Value = value;
        }
    }
}
