// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Dynatrace.Outputs
{

    [OutputType]
    public sealed class MetricEventsQueryDefinitionEntityFilterConditionsCondition
    {
        /// <summary>
        /// Possible Values: `CONTAINS_CASE_SENSITIVE`, `DOES_NOT_CONTAIN_CASE_SENSITIVE`, `DOES_NOT_EQUAL`, `DOES_NOT_START_WITH`, `EQUALS`, `STARTS_WITH`
        /// </summary>
        public readonly string Operator;
        /// <summary>
        /// Possible Values: `AUTO_ADAPTIVE_THRESHOLD`, `SEASONAL_BASELINE`, `STATIC_THRESHOLD`
        /// </summary>
        public readonly string Type;
        /// <summary>
        /// no documentation available
        /// </summary>
        public readonly string Value;

        [OutputConstructor]
        private MetricEventsQueryDefinitionEntityFilterConditionsCondition(
            string @operator,

            string type,

            string value)
        {
            Operator = @operator;
            Type = type;
            Value = value;
        }
    }
}
