// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Dynatrace.Outputs
{

    [OutputType]
    public sealed class OsServicesDetectionConditionsLinuxLinuxDetectionCondition
    {
        /// <summary>
        /// This string has to match a required format. See [OS services monitoring](https://dt-url.net/vl03xzk).
        /// </summary>
        public readonly string? Condition;
        public readonly Outputs.OsServicesDetectionConditionsLinuxLinuxDetectionConditionHostMetadataCondition? HostMetadataCondition;
        public readonly string? Property;
        public readonly string? RuleType;
        public readonly string? StartupCondition;

        [OutputConstructor]
        private OsServicesDetectionConditionsLinuxLinuxDetectionCondition(
            string? condition,

            Outputs.OsServicesDetectionConditionsLinuxLinuxDetectionConditionHostMetadataCondition? hostMetadataCondition,

            string? property,

            string? ruleType,

            string? startupCondition)
        {
            Condition = condition;
            HostMetadataCondition = hostMetadataCondition;
            Property = property;
            RuleType = ruleType;
            StartupCondition = startupCondition;
        }
    }
}
