// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Dynatrace.Outputs
{

    [OutputType]
    public sealed class ProcessAvailabilityRulesRule
    {
        public readonly string? Condition;
        public readonly Outputs.ProcessAvailabilityRulesRuleHostMetadataCondition? HostMetadataCondition;
        public readonly string? Property;
        public readonly string? RuleType;

        [OutputConstructor]
        private ProcessAvailabilityRulesRule(
            string? condition,

            Outputs.ProcessAvailabilityRulesRuleHostMetadataCondition? hostMetadataCondition,

            string? property,

            string? ruleType)
        {
            Condition = condition;
            HostMetadataCondition = hostMetadataCondition;
            Property = property;
            RuleType = ruleType;
        }
    }
}
