// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Dynatrace.Outputs
{

    [OutputType]
    public sealed class WebApplicationMetaDataCaptureSettingsCapture
    {
        /// <summary>
        /// The name of the meta data to capture
        /// </summary>
        public readonly string CapturingName;
        /// <summary>
        /// The name of the conversion goal. Valid length within 1 and 50 characters.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// `true` if this metadata should be captured regardless of the privacy settings, `false` otherwise
        /// </summary>
        public readonly bool? PublicMetadata;
        /// <summary>
        /// The type of the action. Possible values are `Custom`, `Load` and `Xhr`.
        /// </summary>
        public readonly string Type;
        /// <summary>
        /// The unique ID of the meta data to capture
        /// </summary>
        public readonly int? UniqueId;
        /// <summary>
        /// `true` if the last captured value should be used for this metadata. By default the first value will be used.
        /// </summary>
        public readonly bool? UseLastValue;

        [OutputConstructor]
        private WebApplicationMetaDataCaptureSettingsCapture(
            string capturingName,

            string name,

            bool? publicMetadata,

            string type,

            int? uniqueId,

            bool? useLastValue)
        {
            CapturingName = capturingName;
            Name = name;
            PublicMetadata = publicMetadata;
            Type = type;
            UniqueId = uniqueId;
            UseLastValue = useLastValue;
        }
    }
}
