// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Dynatrace.Outputs
{

    [OutputType]
    public sealed class WebApplicationMonitoringSettingsAdvancedJavascriptTagSettingsGlobalEventCaptureSettings
    {
        /// <summary>
        /// Additional events to be captured globally as user input.
        /// </summary>
        public readonly string? AdditionalEventCapturedAsUserInput;
        /// <summary>
        /// Change event handler enabled/disabled
        /// </summary>
        public readonly bool? Change;
        /// <summary>
        /// Click event handler enabled/disabled
        /// </summary>
        public readonly bool? Click;
        public readonly bool? Doubleclick;
        public readonly bool? Keydown;
        public readonly bool? Keyup;
        public readonly bool? Mousedown;
        /// <summary>
        /// Mouseup event handler enabled/disabled
        /// </summary>
        public readonly bool? Mouseup;
        public readonly bool? Scroll;
        /// <summary>
        /// TouchEnd enabled/disabled
        /// </summary>
        public readonly bool? TouchEnd;
        /// <summary>
        /// TouchStart enabled/disabled
        /// </summary>
        public readonly bool? TouchStart;

        [OutputConstructor]
        private WebApplicationMonitoringSettingsAdvancedJavascriptTagSettingsGlobalEventCaptureSettings(
            string? additionalEventCapturedAsUserInput,

            bool? change,

            bool? click,

            bool? doubleclick,

            bool? keydown,

            bool? keyup,

            bool? mousedown,

            bool? mouseup,

            bool? scroll,

            bool? touchEnd,

            bool? touchStart)
        {
            AdditionalEventCapturedAsUserInput = additionalEventCapturedAsUserInput;
            Change = change;
            Click = click;
            Doubleclick = doubleclick;
            Keydown = keydown;
            Keyup = keyup;
            Mousedown = mousedown;
            Mouseup = mouseup;
            Scroll = scroll;
            TouchEnd = touchEnd;
            TouchStart = touchStart;
        }
    }
}
