// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Dynatrace.Outputs
{

    [OutputType]
    public sealed class WebApplicationUserTagsTag
    {
        /// <summary>
        /// Cleanup rule expression of the userTag
        /// </summary>
        public readonly string? CleanupRule;
        /// <summary>
        /// The ID of conversion goal.
        /// </summary>
        public readonly int? Id;
        /// <summary>
        /// Case insensitive naming
        /// </summary>
        public readonly bool? IgnoreCase;
        /// <summary>
        /// The ID of the metadata
        /// </summary>
        public readonly int? MetadataId;
        /// <summary>
        /// The ID of the RrequestAttribute for the userTag
        /// </summary>
        public readonly string? ServerSideRequestAttribute;
        /// <summary>
        /// The unique ID of the meta data to capture
        /// </summary>
        public readonly int? UniqueId;

        [OutputConstructor]
        private WebApplicationUserTagsTag(
            string? cleanupRule,

            int? id,

            bool? ignoreCase,

            int? metadataId,

            string? serverSideRequestAttribute,

            int? uniqueId)
        {
            CleanupRule = cleanupRule;
            Id = id;
            IgnoreCase = ignoreCase;
            MetadataId = metadataId;
            ServerSideRequestAttribute = serverSideRequestAttribute;
            UniqueId = uniqueId;
        }
    }
}
