// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Dynatrace.Outputs
{

    [OutputType]
    public sealed class WebApplicationUserActionAndSessionPropertiesProperty
    {
        /// <summary>
        /// The aggregation type of the property.
        /// </summary>
        public readonly string? Aggregation;
        /// <summary>
        /// Cleanup rule expression of the userTag
        /// </summary>
        public readonly string? CleanupRule;
        public readonly string? DisplayName;
        /// <summary>
        /// The ID of conversion goal.
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// Case insensitive naming
        /// </summary>
        public readonly bool? IgnoreCase;
        /// <summary>
        /// Key of the property
        /// </summary>
        public readonly string Key;
        public readonly int? LongStringLength;
        /// <summary>
        /// The ID of the metadata
        /// </summary>
        public readonly int? MetadataId;
        /// <summary>
        /// The origin of the property. Possible values are `JAVASCRIPT_API`, `META_DATA` and `SERVER_SIDE_REQUEST_ATTRIBUTE`.
        /// </summary>
        public readonly string Origin;
        /// <summary>
        /// The ID of the RrequestAttribute for the userTag
        /// </summary>
        public readonly string? ServerSideRequestAttribute;
        public readonly bool? StoreAsSessionProperty;
        public readonly bool? StoreAsUserActionProperty;
        /// <summary>
        /// The type of the action. Possible values are `Custom`, `Load` and `Xhr`.
        /// </summary>
        public readonly string Type;

        [OutputConstructor]
        private WebApplicationUserActionAndSessionPropertiesProperty(
            string? aggregation,

            string? cleanupRule,

            string? displayName,

            int id,

            bool? ignoreCase,

            string key,

            int? longStringLength,

            int? metadataId,

            string origin,

            string? serverSideRequestAttribute,

            bool? storeAsSessionProperty,

            bool? storeAsUserActionProperty,

            string type)
        {
            Aggregation = aggregation;
            CleanupRule = cleanupRule;
            DisplayName = displayName;
            Id = id;
            IgnoreCase = ignoreCase;
            Key = key;
            LongStringLength = longStringLength;
            MetadataId = metadataId;
            Origin = origin;
            ServerSideRequestAttribute = serverSideRequestAttribute;
            StoreAsSessionProperty = storeAsSessionProperty;
            StoreAsUserActionProperty = storeAsUserActionProperty;
            Type = type;
        }
    }
}
