// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Dynatrace
{
    public static class GetDocuments
    {
        /// <summary>
        /// Retrieve a list of all documents.
        /// </summary>
        public static Task<GetDocumentsResult> InvokeAsync(GetDocumentsArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetDocumentsResult>("dynatrace:index/getDocuments:getDocuments", args ?? new GetDocumentsArgs(), options.WithDefaults());

        /// <summary>
        /// Retrieve a list of all documents.
        /// </summary>
        public static Output<GetDocumentsResult> Invoke(GetDocumentsInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetDocumentsResult>("dynatrace:index/getDocuments:getDocuments", args ?? new GetDocumentsInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetDocumentsArgs : global::Pulumi.InvokeArgs
    {
        [Input("type")]
        public string? Type { get; set; }

        public GetDocumentsArgs()
        {
        }
        public static new GetDocumentsArgs Empty => new GetDocumentsArgs();
    }

    public sealed class GetDocumentsInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("type")]
        public Input<string>? Type { get; set; }

        public GetDocumentsInvokeArgs()
        {
        }
        public static new GetDocumentsInvokeArgs Empty => new GetDocumentsInvokeArgs();
    }


    [OutputType]
    public sealed class GetDocumentsResult
    {
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The type of documents to query for. Leave empty if you want to query for all kinds of documents. Possible values are `document` or `notebook`
        /// </summary>
        public readonly string? Type;
        public readonly ImmutableArray<Outputs.GetDocumentsValueResult> Values;

        [OutputConstructor]
        private GetDocumentsResult(
            string id,

            string? type,

            ImmutableArray<Outputs.GetDocumentsValueResult> values)
        {
            Id = id;
            Type = type;
            Values = values;
        }
    }
}
