// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package dynatrace

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-dynatrace/sdk/go/dynatrace/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

var _ = internal.GetEnvOrDefault

type GetDocumentsValue struct {
	Id    string `pulumi:"id"`
	Name  string `pulumi:"name"`
	Owner string `pulumi:"owner"`
	Type  string `pulumi:"type"`
}

// GetDocumentsValueInput is an input type that accepts GetDocumentsValueArgs and GetDocumentsValueOutput values.
// You can construct a concrete instance of `GetDocumentsValueInput` via:
//
//	GetDocumentsValueArgs{...}
type GetDocumentsValueInput interface {
	pulumi.Input

	ToGetDocumentsValueOutput() GetDocumentsValueOutput
	ToGetDocumentsValueOutputWithContext(context.Context) GetDocumentsValueOutput
}

type GetDocumentsValueArgs struct {
	Id    pulumi.StringInput `pulumi:"id"`
	Name  pulumi.StringInput `pulumi:"name"`
	Owner pulumi.StringInput `pulumi:"owner"`
	Type  pulumi.StringInput `pulumi:"type"`
}

func (GetDocumentsValueArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetDocumentsValue)(nil)).Elem()
}

func (i GetDocumentsValueArgs) ToGetDocumentsValueOutput() GetDocumentsValueOutput {
	return i.ToGetDocumentsValueOutputWithContext(context.Background())
}

func (i GetDocumentsValueArgs) ToGetDocumentsValueOutputWithContext(ctx context.Context) GetDocumentsValueOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetDocumentsValueOutput)
}

// GetDocumentsValueArrayInput is an input type that accepts GetDocumentsValueArray and GetDocumentsValueArrayOutput values.
// You can construct a concrete instance of `GetDocumentsValueArrayInput` via:
//
//	GetDocumentsValueArray{ GetDocumentsValueArgs{...} }
type GetDocumentsValueArrayInput interface {
	pulumi.Input

	ToGetDocumentsValueArrayOutput() GetDocumentsValueArrayOutput
	ToGetDocumentsValueArrayOutputWithContext(context.Context) GetDocumentsValueArrayOutput
}

type GetDocumentsValueArray []GetDocumentsValueInput

func (GetDocumentsValueArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetDocumentsValue)(nil)).Elem()
}

func (i GetDocumentsValueArray) ToGetDocumentsValueArrayOutput() GetDocumentsValueArrayOutput {
	return i.ToGetDocumentsValueArrayOutputWithContext(context.Background())
}

func (i GetDocumentsValueArray) ToGetDocumentsValueArrayOutputWithContext(ctx context.Context) GetDocumentsValueArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetDocumentsValueArrayOutput)
}

type GetDocumentsValueOutput struct{ *pulumi.OutputState }

func (GetDocumentsValueOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetDocumentsValue)(nil)).Elem()
}

func (o GetDocumentsValueOutput) ToGetDocumentsValueOutput() GetDocumentsValueOutput {
	return o
}

func (o GetDocumentsValueOutput) ToGetDocumentsValueOutputWithContext(ctx context.Context) GetDocumentsValueOutput {
	return o
}

func (o GetDocumentsValueOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetDocumentsValue) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetDocumentsValueOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetDocumentsValue) string { return v.Name }).(pulumi.StringOutput)
}

func (o GetDocumentsValueOutput) Owner() pulumi.StringOutput {
	return o.ApplyT(func(v GetDocumentsValue) string { return v.Owner }).(pulumi.StringOutput)
}

func (o GetDocumentsValueOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v GetDocumentsValue) string { return v.Type }).(pulumi.StringOutput)
}

type GetDocumentsValueArrayOutput struct{ *pulumi.OutputState }

func (GetDocumentsValueArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetDocumentsValue)(nil)).Elem()
}

func (o GetDocumentsValueArrayOutput) ToGetDocumentsValueArrayOutput() GetDocumentsValueArrayOutput {
	return o
}

func (o GetDocumentsValueArrayOutput) ToGetDocumentsValueArrayOutputWithContext(ctx context.Context) GetDocumentsValueArrayOutput {
	return o
}

func (o GetDocumentsValueArrayOutput) Index(i pulumi.IntInput) GetDocumentsValueOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetDocumentsValue {
		return vs[0].([]GetDocumentsValue)[vs[1].(int)]
	}).(GetDocumentsValueOutput)
}

type GetEntitiesEntity struct {
	DisplayName *string                `pulumi:"displayName"`
	EntityId    *string                `pulumi:"entityId"`
	LastSeenTms *int                   `pulumi:"lastSeenTms"`
	Properties  map[string]string      `pulumi:"properties"`
	Tags        []GetEntitiesEntityTag `pulumi:"tags"`
	Type        *string                `pulumi:"type"`
}

// GetEntitiesEntityInput is an input type that accepts GetEntitiesEntityArgs and GetEntitiesEntityOutput values.
// You can construct a concrete instance of `GetEntitiesEntityInput` via:
//
//	GetEntitiesEntityArgs{...}
type GetEntitiesEntityInput interface {
	pulumi.Input

	ToGetEntitiesEntityOutput() GetEntitiesEntityOutput
	ToGetEntitiesEntityOutputWithContext(context.Context) GetEntitiesEntityOutput
}

type GetEntitiesEntityArgs struct {
	DisplayName pulumi.StringPtrInput          `pulumi:"displayName"`
	EntityId    pulumi.StringPtrInput          `pulumi:"entityId"`
	LastSeenTms pulumi.IntPtrInput             `pulumi:"lastSeenTms"`
	Properties  pulumi.StringMapInput          `pulumi:"properties"`
	Tags        GetEntitiesEntityTagArrayInput `pulumi:"tags"`
	Type        pulumi.StringPtrInput          `pulumi:"type"`
}

func (GetEntitiesEntityArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetEntitiesEntity)(nil)).Elem()
}

func (i GetEntitiesEntityArgs) ToGetEntitiesEntityOutput() GetEntitiesEntityOutput {
	return i.ToGetEntitiesEntityOutputWithContext(context.Background())
}

func (i GetEntitiesEntityArgs) ToGetEntitiesEntityOutputWithContext(ctx context.Context) GetEntitiesEntityOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetEntitiesEntityOutput)
}

// GetEntitiesEntityArrayInput is an input type that accepts GetEntitiesEntityArray and GetEntitiesEntityArrayOutput values.
// You can construct a concrete instance of `GetEntitiesEntityArrayInput` via:
//
//	GetEntitiesEntityArray{ GetEntitiesEntityArgs{...} }
type GetEntitiesEntityArrayInput interface {
	pulumi.Input

	ToGetEntitiesEntityArrayOutput() GetEntitiesEntityArrayOutput
	ToGetEntitiesEntityArrayOutputWithContext(context.Context) GetEntitiesEntityArrayOutput
}

type GetEntitiesEntityArray []GetEntitiesEntityInput

func (GetEntitiesEntityArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetEntitiesEntity)(nil)).Elem()
}

func (i GetEntitiesEntityArray) ToGetEntitiesEntityArrayOutput() GetEntitiesEntityArrayOutput {
	return i.ToGetEntitiesEntityArrayOutputWithContext(context.Background())
}

func (i GetEntitiesEntityArray) ToGetEntitiesEntityArrayOutputWithContext(ctx context.Context) GetEntitiesEntityArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetEntitiesEntityArrayOutput)
}

type GetEntitiesEntityOutput struct{ *pulumi.OutputState }

func (GetEntitiesEntityOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetEntitiesEntity)(nil)).Elem()
}

func (o GetEntitiesEntityOutput) ToGetEntitiesEntityOutput() GetEntitiesEntityOutput {
	return o
}

func (o GetEntitiesEntityOutput) ToGetEntitiesEntityOutputWithContext(ctx context.Context) GetEntitiesEntityOutput {
	return o
}

func (o GetEntitiesEntityOutput) DisplayName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetEntitiesEntity) *string { return v.DisplayName }).(pulumi.StringPtrOutput)
}

func (o GetEntitiesEntityOutput) EntityId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetEntitiesEntity) *string { return v.EntityId }).(pulumi.StringPtrOutput)
}

func (o GetEntitiesEntityOutput) LastSeenTms() pulumi.IntPtrOutput {
	return o.ApplyT(func(v GetEntitiesEntity) *int { return v.LastSeenTms }).(pulumi.IntPtrOutput)
}

func (o GetEntitiesEntityOutput) Properties() pulumi.StringMapOutput {
	return o.ApplyT(func(v GetEntitiesEntity) map[string]string { return v.Properties }).(pulumi.StringMapOutput)
}

func (o GetEntitiesEntityOutput) Tags() GetEntitiesEntityTagArrayOutput {
	return o.ApplyT(func(v GetEntitiesEntity) []GetEntitiesEntityTag { return v.Tags }).(GetEntitiesEntityTagArrayOutput)
}

func (o GetEntitiesEntityOutput) Type() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetEntitiesEntity) *string { return v.Type }).(pulumi.StringPtrOutput)
}

type GetEntitiesEntityArrayOutput struct{ *pulumi.OutputState }

func (GetEntitiesEntityArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetEntitiesEntity)(nil)).Elem()
}

func (o GetEntitiesEntityArrayOutput) ToGetEntitiesEntityArrayOutput() GetEntitiesEntityArrayOutput {
	return o
}

func (o GetEntitiesEntityArrayOutput) ToGetEntitiesEntityArrayOutputWithContext(ctx context.Context) GetEntitiesEntityArrayOutput {
	return o
}

func (o GetEntitiesEntityArrayOutput) Index(i pulumi.IntInput) GetEntitiesEntityOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetEntitiesEntity {
		return vs[0].([]GetEntitiesEntity)[vs[1].(int)]
	}).(GetEntitiesEntityOutput)
}

type GetEntitiesEntityTag struct {
	Tags []GetEntitiesEntityTagTag `pulumi:"tags"`
}

// GetEntitiesEntityTagInput is an input type that accepts GetEntitiesEntityTagArgs and GetEntitiesEntityTagOutput values.
// You can construct a concrete instance of `GetEntitiesEntityTagInput` via:
//
//	GetEntitiesEntityTagArgs{...}
type GetEntitiesEntityTagInput interface {
	pulumi.Input

	ToGetEntitiesEntityTagOutput() GetEntitiesEntityTagOutput
	ToGetEntitiesEntityTagOutputWithContext(context.Context) GetEntitiesEntityTagOutput
}

type GetEntitiesEntityTagArgs struct {
	Tags GetEntitiesEntityTagTagArrayInput `pulumi:"tags"`
}

func (GetEntitiesEntityTagArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetEntitiesEntityTag)(nil)).Elem()
}

func (i GetEntitiesEntityTagArgs) ToGetEntitiesEntityTagOutput() GetEntitiesEntityTagOutput {
	return i.ToGetEntitiesEntityTagOutputWithContext(context.Background())
}

func (i GetEntitiesEntityTagArgs) ToGetEntitiesEntityTagOutputWithContext(ctx context.Context) GetEntitiesEntityTagOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetEntitiesEntityTagOutput)
}

// GetEntitiesEntityTagArrayInput is an input type that accepts GetEntitiesEntityTagArray and GetEntitiesEntityTagArrayOutput values.
// You can construct a concrete instance of `GetEntitiesEntityTagArrayInput` via:
//
//	GetEntitiesEntityTagArray{ GetEntitiesEntityTagArgs{...} }
type GetEntitiesEntityTagArrayInput interface {
	pulumi.Input

	ToGetEntitiesEntityTagArrayOutput() GetEntitiesEntityTagArrayOutput
	ToGetEntitiesEntityTagArrayOutputWithContext(context.Context) GetEntitiesEntityTagArrayOutput
}

type GetEntitiesEntityTagArray []GetEntitiesEntityTagInput

func (GetEntitiesEntityTagArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetEntitiesEntityTag)(nil)).Elem()
}

func (i GetEntitiesEntityTagArray) ToGetEntitiesEntityTagArrayOutput() GetEntitiesEntityTagArrayOutput {
	return i.ToGetEntitiesEntityTagArrayOutputWithContext(context.Background())
}

func (i GetEntitiesEntityTagArray) ToGetEntitiesEntityTagArrayOutputWithContext(ctx context.Context) GetEntitiesEntityTagArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetEntitiesEntityTagArrayOutput)
}

type GetEntitiesEntityTagOutput struct{ *pulumi.OutputState }

func (GetEntitiesEntityTagOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetEntitiesEntityTag)(nil)).Elem()
}

func (o GetEntitiesEntityTagOutput) ToGetEntitiesEntityTagOutput() GetEntitiesEntityTagOutput {
	return o
}

func (o GetEntitiesEntityTagOutput) ToGetEntitiesEntityTagOutputWithContext(ctx context.Context) GetEntitiesEntityTagOutput {
	return o
}

func (o GetEntitiesEntityTagOutput) Tags() GetEntitiesEntityTagTagArrayOutput {
	return o.ApplyT(func(v GetEntitiesEntityTag) []GetEntitiesEntityTagTag { return v.Tags }).(GetEntitiesEntityTagTagArrayOutput)
}

type GetEntitiesEntityTagArrayOutput struct{ *pulumi.OutputState }

func (GetEntitiesEntityTagArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetEntitiesEntityTag)(nil)).Elem()
}

func (o GetEntitiesEntityTagArrayOutput) ToGetEntitiesEntityTagArrayOutput() GetEntitiesEntityTagArrayOutput {
	return o
}

func (o GetEntitiesEntityTagArrayOutput) ToGetEntitiesEntityTagArrayOutputWithContext(ctx context.Context) GetEntitiesEntityTagArrayOutput {
	return o
}

func (o GetEntitiesEntityTagArrayOutput) Index(i pulumi.IntInput) GetEntitiesEntityTagOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetEntitiesEntityTag {
		return vs[0].([]GetEntitiesEntityTag)[vs[1].(int)]
	}).(GetEntitiesEntityTagOutput)
}

type GetEntitiesEntityTagTag struct {
	Context              string  `pulumi:"context"`
	Key                  string  `pulumi:"key"`
	StringRepresentation *string `pulumi:"stringRepresentation"`
	Value                *string `pulumi:"value"`
}

// GetEntitiesEntityTagTagInput is an input type that accepts GetEntitiesEntityTagTagArgs and GetEntitiesEntityTagTagOutput values.
// You can construct a concrete instance of `GetEntitiesEntityTagTagInput` via:
//
//	GetEntitiesEntityTagTagArgs{...}
type GetEntitiesEntityTagTagInput interface {
	pulumi.Input

	ToGetEntitiesEntityTagTagOutput() GetEntitiesEntityTagTagOutput
	ToGetEntitiesEntityTagTagOutputWithContext(context.Context) GetEntitiesEntityTagTagOutput
}

type GetEntitiesEntityTagTagArgs struct {
	Context              pulumi.StringInput    `pulumi:"context"`
	Key                  pulumi.StringInput    `pulumi:"key"`
	StringRepresentation pulumi.StringPtrInput `pulumi:"stringRepresentation"`
	Value                pulumi.StringPtrInput `pulumi:"value"`
}

func (GetEntitiesEntityTagTagArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetEntitiesEntityTagTag)(nil)).Elem()
}

func (i GetEntitiesEntityTagTagArgs) ToGetEntitiesEntityTagTagOutput() GetEntitiesEntityTagTagOutput {
	return i.ToGetEntitiesEntityTagTagOutputWithContext(context.Background())
}

func (i GetEntitiesEntityTagTagArgs) ToGetEntitiesEntityTagTagOutputWithContext(ctx context.Context) GetEntitiesEntityTagTagOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetEntitiesEntityTagTagOutput)
}

// GetEntitiesEntityTagTagArrayInput is an input type that accepts GetEntitiesEntityTagTagArray and GetEntitiesEntityTagTagArrayOutput values.
// You can construct a concrete instance of `GetEntitiesEntityTagTagArrayInput` via:
//
//	GetEntitiesEntityTagTagArray{ GetEntitiesEntityTagTagArgs{...} }
type GetEntitiesEntityTagTagArrayInput interface {
	pulumi.Input

	ToGetEntitiesEntityTagTagArrayOutput() GetEntitiesEntityTagTagArrayOutput
	ToGetEntitiesEntityTagTagArrayOutputWithContext(context.Context) GetEntitiesEntityTagTagArrayOutput
}

type GetEntitiesEntityTagTagArray []GetEntitiesEntityTagTagInput

func (GetEntitiesEntityTagTagArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetEntitiesEntityTagTag)(nil)).Elem()
}

func (i GetEntitiesEntityTagTagArray) ToGetEntitiesEntityTagTagArrayOutput() GetEntitiesEntityTagTagArrayOutput {
	return i.ToGetEntitiesEntityTagTagArrayOutputWithContext(context.Background())
}

func (i GetEntitiesEntityTagTagArray) ToGetEntitiesEntityTagTagArrayOutputWithContext(ctx context.Context) GetEntitiesEntityTagTagArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetEntitiesEntityTagTagArrayOutput)
}

type GetEntitiesEntityTagTagOutput struct{ *pulumi.OutputState }

func (GetEntitiesEntityTagTagOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetEntitiesEntityTagTag)(nil)).Elem()
}

func (o GetEntitiesEntityTagTagOutput) ToGetEntitiesEntityTagTagOutput() GetEntitiesEntityTagTagOutput {
	return o
}

func (o GetEntitiesEntityTagTagOutput) ToGetEntitiesEntityTagTagOutputWithContext(ctx context.Context) GetEntitiesEntityTagTagOutput {
	return o
}

func (o GetEntitiesEntityTagTagOutput) Context() pulumi.StringOutput {
	return o.ApplyT(func(v GetEntitiesEntityTagTag) string { return v.Context }).(pulumi.StringOutput)
}

func (o GetEntitiesEntityTagTagOutput) Key() pulumi.StringOutput {
	return o.ApplyT(func(v GetEntitiesEntityTagTag) string { return v.Key }).(pulumi.StringOutput)
}

func (o GetEntitiesEntityTagTagOutput) StringRepresentation() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetEntitiesEntityTagTag) *string { return v.StringRepresentation }).(pulumi.StringPtrOutput)
}

func (o GetEntitiesEntityTagTagOutput) Value() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetEntitiesEntityTagTag) *string { return v.Value }).(pulumi.StringPtrOutput)
}

type GetEntitiesEntityTagTagArrayOutput struct{ *pulumi.OutputState }

func (GetEntitiesEntityTagTagArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetEntitiesEntityTagTag)(nil)).Elem()
}

func (o GetEntitiesEntityTagTagArrayOutput) ToGetEntitiesEntityTagTagArrayOutput() GetEntitiesEntityTagTagArrayOutput {
	return o
}

func (o GetEntitiesEntityTagTagArrayOutput) ToGetEntitiesEntityTagTagArrayOutputWithContext(ctx context.Context) GetEntitiesEntityTagTagArrayOutput {
	return o
}

func (o GetEntitiesEntityTagTagArrayOutput) Index(i pulumi.IntInput) GetEntitiesEntityTagTagOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetEntitiesEntityTagTag {
		return vs[0].([]GetEntitiesEntityTagTag)[vs[1].(int)]
	}).(GetEntitiesEntityTagTagOutput)
}

type GetHubItemsItem struct {
	ActivationLink       string   `pulumi:"activationLink"`
	ArtifactId           string   `pulumi:"artifactId"`
	AuthorLogo           string   `pulumi:"authorLogo"`
	AuthorName           string   `pulumi:"authorName"`
	ClusterCompatible    bool     `pulumi:"clusterCompatible"`
	ComingSoon           bool     `pulumi:"comingSoon"`
	Description          string   `pulumi:"description"`
	DocumentationLink    string   `pulumi:"documentationLink"`
	HasDescriptionBlocks bool     `pulumi:"hasDescriptionBlocks"`
	ItemId               string   `pulumi:"itemId"`
	Logo                 string   `pulumi:"logo"`
	MarketingLink        string   `pulumi:"marketingLink"`
	Name                 string   `pulumi:"name"`
	NotCompatibleReason  string   `pulumi:"notCompatibleReason"`
	Tags                 []string `pulumi:"tags"`
	Type                 string   `pulumi:"type"`
}

// GetHubItemsItemInput is an input type that accepts GetHubItemsItemArgs and GetHubItemsItemOutput values.
// You can construct a concrete instance of `GetHubItemsItemInput` via:
//
//	GetHubItemsItemArgs{...}
type GetHubItemsItemInput interface {
	pulumi.Input

	ToGetHubItemsItemOutput() GetHubItemsItemOutput
	ToGetHubItemsItemOutputWithContext(context.Context) GetHubItemsItemOutput
}

type GetHubItemsItemArgs struct {
	ActivationLink       pulumi.StringInput      `pulumi:"activationLink"`
	ArtifactId           pulumi.StringInput      `pulumi:"artifactId"`
	AuthorLogo           pulumi.StringInput      `pulumi:"authorLogo"`
	AuthorName           pulumi.StringInput      `pulumi:"authorName"`
	ClusterCompatible    pulumi.BoolInput        `pulumi:"clusterCompatible"`
	ComingSoon           pulumi.BoolInput        `pulumi:"comingSoon"`
	Description          pulumi.StringInput      `pulumi:"description"`
	DocumentationLink    pulumi.StringInput      `pulumi:"documentationLink"`
	HasDescriptionBlocks pulumi.BoolInput        `pulumi:"hasDescriptionBlocks"`
	ItemId               pulumi.StringInput      `pulumi:"itemId"`
	Logo                 pulumi.StringInput      `pulumi:"logo"`
	MarketingLink        pulumi.StringInput      `pulumi:"marketingLink"`
	Name                 pulumi.StringInput      `pulumi:"name"`
	NotCompatibleReason  pulumi.StringInput      `pulumi:"notCompatibleReason"`
	Tags                 pulumi.StringArrayInput `pulumi:"tags"`
	Type                 pulumi.StringInput      `pulumi:"type"`
}

func (GetHubItemsItemArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetHubItemsItem)(nil)).Elem()
}

func (i GetHubItemsItemArgs) ToGetHubItemsItemOutput() GetHubItemsItemOutput {
	return i.ToGetHubItemsItemOutputWithContext(context.Background())
}

func (i GetHubItemsItemArgs) ToGetHubItemsItemOutputWithContext(ctx context.Context) GetHubItemsItemOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetHubItemsItemOutput)
}

// GetHubItemsItemArrayInput is an input type that accepts GetHubItemsItemArray and GetHubItemsItemArrayOutput values.
// You can construct a concrete instance of `GetHubItemsItemArrayInput` via:
//
//	GetHubItemsItemArray{ GetHubItemsItemArgs{...} }
type GetHubItemsItemArrayInput interface {
	pulumi.Input

	ToGetHubItemsItemArrayOutput() GetHubItemsItemArrayOutput
	ToGetHubItemsItemArrayOutputWithContext(context.Context) GetHubItemsItemArrayOutput
}

type GetHubItemsItemArray []GetHubItemsItemInput

func (GetHubItemsItemArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetHubItemsItem)(nil)).Elem()
}

func (i GetHubItemsItemArray) ToGetHubItemsItemArrayOutput() GetHubItemsItemArrayOutput {
	return i.ToGetHubItemsItemArrayOutputWithContext(context.Background())
}

func (i GetHubItemsItemArray) ToGetHubItemsItemArrayOutputWithContext(ctx context.Context) GetHubItemsItemArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetHubItemsItemArrayOutput)
}

type GetHubItemsItemOutput struct{ *pulumi.OutputState }

func (GetHubItemsItemOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetHubItemsItem)(nil)).Elem()
}

func (o GetHubItemsItemOutput) ToGetHubItemsItemOutput() GetHubItemsItemOutput {
	return o
}

func (o GetHubItemsItemOutput) ToGetHubItemsItemOutputWithContext(ctx context.Context) GetHubItemsItemOutput {
	return o
}

func (o GetHubItemsItemOutput) ActivationLink() pulumi.StringOutput {
	return o.ApplyT(func(v GetHubItemsItem) string { return v.ActivationLink }).(pulumi.StringOutput)
}

func (o GetHubItemsItemOutput) ArtifactId() pulumi.StringOutput {
	return o.ApplyT(func(v GetHubItemsItem) string { return v.ArtifactId }).(pulumi.StringOutput)
}

func (o GetHubItemsItemOutput) AuthorLogo() pulumi.StringOutput {
	return o.ApplyT(func(v GetHubItemsItem) string { return v.AuthorLogo }).(pulumi.StringOutput)
}

func (o GetHubItemsItemOutput) AuthorName() pulumi.StringOutput {
	return o.ApplyT(func(v GetHubItemsItem) string { return v.AuthorName }).(pulumi.StringOutput)
}

func (o GetHubItemsItemOutput) ClusterCompatible() pulumi.BoolOutput {
	return o.ApplyT(func(v GetHubItemsItem) bool { return v.ClusterCompatible }).(pulumi.BoolOutput)
}

func (o GetHubItemsItemOutput) ComingSoon() pulumi.BoolOutput {
	return o.ApplyT(func(v GetHubItemsItem) bool { return v.ComingSoon }).(pulumi.BoolOutput)
}

func (o GetHubItemsItemOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v GetHubItemsItem) string { return v.Description }).(pulumi.StringOutput)
}

func (o GetHubItemsItemOutput) DocumentationLink() pulumi.StringOutput {
	return o.ApplyT(func(v GetHubItemsItem) string { return v.DocumentationLink }).(pulumi.StringOutput)
}

func (o GetHubItemsItemOutput) HasDescriptionBlocks() pulumi.BoolOutput {
	return o.ApplyT(func(v GetHubItemsItem) bool { return v.HasDescriptionBlocks }).(pulumi.BoolOutput)
}

func (o GetHubItemsItemOutput) ItemId() pulumi.StringOutput {
	return o.ApplyT(func(v GetHubItemsItem) string { return v.ItemId }).(pulumi.StringOutput)
}

func (o GetHubItemsItemOutput) Logo() pulumi.StringOutput {
	return o.ApplyT(func(v GetHubItemsItem) string { return v.Logo }).(pulumi.StringOutput)
}

func (o GetHubItemsItemOutput) MarketingLink() pulumi.StringOutput {
	return o.ApplyT(func(v GetHubItemsItem) string { return v.MarketingLink }).(pulumi.StringOutput)
}

func (o GetHubItemsItemOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetHubItemsItem) string { return v.Name }).(pulumi.StringOutput)
}

func (o GetHubItemsItemOutput) NotCompatibleReason() pulumi.StringOutput {
	return o.ApplyT(func(v GetHubItemsItem) string { return v.NotCompatibleReason }).(pulumi.StringOutput)
}

func (o GetHubItemsItemOutput) Tags() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetHubItemsItem) []string { return v.Tags }).(pulumi.StringArrayOutput)
}

func (o GetHubItemsItemOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v GetHubItemsItem) string { return v.Type }).(pulumi.StringOutput)
}

type GetHubItemsItemArrayOutput struct{ *pulumi.OutputState }

func (GetHubItemsItemArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetHubItemsItem)(nil)).Elem()
}

func (o GetHubItemsItemArrayOutput) ToGetHubItemsItemArrayOutput() GetHubItemsItemArrayOutput {
	return o
}

func (o GetHubItemsItemArrayOutput) ToGetHubItemsItemArrayOutputWithContext(ctx context.Context) GetHubItemsItemArrayOutput {
	return o
}

func (o GetHubItemsItemArrayOutput) Index(i pulumi.IntInput) GetHubItemsItemOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetHubItemsItem {
		return vs[0].([]GetHubItemsItem)[vs[1].(int)]
	}).(GetHubItemsItemOutput)
}

type GetManagementZonesValue struct {
	Description string `pulumi:"description"`
	Id          string `pulumi:"id"`
	LegacyId    string `pulumi:"legacyId"`
	Name        string `pulumi:"name"`
}

// GetManagementZonesValueInput is an input type that accepts GetManagementZonesValueArgs and GetManagementZonesValueOutput values.
// You can construct a concrete instance of `GetManagementZonesValueInput` via:
//
//	GetManagementZonesValueArgs{...}
type GetManagementZonesValueInput interface {
	pulumi.Input

	ToGetManagementZonesValueOutput() GetManagementZonesValueOutput
	ToGetManagementZonesValueOutputWithContext(context.Context) GetManagementZonesValueOutput
}

type GetManagementZonesValueArgs struct {
	Description pulumi.StringInput `pulumi:"description"`
	Id          pulumi.StringInput `pulumi:"id"`
	LegacyId    pulumi.StringInput `pulumi:"legacyId"`
	Name        pulumi.StringInput `pulumi:"name"`
}

func (GetManagementZonesValueArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetManagementZonesValue)(nil)).Elem()
}

func (i GetManagementZonesValueArgs) ToGetManagementZonesValueOutput() GetManagementZonesValueOutput {
	return i.ToGetManagementZonesValueOutputWithContext(context.Background())
}

func (i GetManagementZonesValueArgs) ToGetManagementZonesValueOutputWithContext(ctx context.Context) GetManagementZonesValueOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetManagementZonesValueOutput)
}

// GetManagementZonesValueArrayInput is an input type that accepts GetManagementZonesValueArray and GetManagementZonesValueArrayOutput values.
// You can construct a concrete instance of `GetManagementZonesValueArrayInput` via:
//
//	GetManagementZonesValueArray{ GetManagementZonesValueArgs{...} }
type GetManagementZonesValueArrayInput interface {
	pulumi.Input

	ToGetManagementZonesValueArrayOutput() GetManagementZonesValueArrayOutput
	ToGetManagementZonesValueArrayOutputWithContext(context.Context) GetManagementZonesValueArrayOutput
}

type GetManagementZonesValueArray []GetManagementZonesValueInput

func (GetManagementZonesValueArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetManagementZonesValue)(nil)).Elem()
}

func (i GetManagementZonesValueArray) ToGetManagementZonesValueArrayOutput() GetManagementZonesValueArrayOutput {
	return i.ToGetManagementZonesValueArrayOutputWithContext(context.Background())
}

func (i GetManagementZonesValueArray) ToGetManagementZonesValueArrayOutputWithContext(ctx context.Context) GetManagementZonesValueArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetManagementZonesValueArrayOutput)
}

type GetManagementZonesValueOutput struct{ *pulumi.OutputState }

func (GetManagementZonesValueOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetManagementZonesValue)(nil)).Elem()
}

func (o GetManagementZonesValueOutput) ToGetManagementZonesValueOutput() GetManagementZonesValueOutput {
	return o
}

func (o GetManagementZonesValueOutput) ToGetManagementZonesValueOutputWithContext(ctx context.Context) GetManagementZonesValueOutput {
	return o
}

func (o GetManagementZonesValueOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v GetManagementZonesValue) string { return v.Description }).(pulumi.StringOutput)
}

func (o GetManagementZonesValueOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetManagementZonesValue) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetManagementZonesValueOutput) LegacyId() pulumi.StringOutput {
	return o.ApplyT(func(v GetManagementZonesValue) string { return v.LegacyId }).(pulumi.StringOutput)
}

func (o GetManagementZonesValueOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetManagementZonesValue) string { return v.Name }).(pulumi.StringOutput)
}

type GetManagementZonesValueArrayOutput struct{ *pulumi.OutputState }

func (GetManagementZonesValueArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetManagementZonesValue)(nil)).Elem()
}

func (o GetManagementZonesValueArrayOutput) ToGetManagementZonesValueArrayOutput() GetManagementZonesValueArrayOutput {
	return o
}

func (o GetManagementZonesValueArrayOutput) ToGetManagementZonesValueArrayOutputWithContext(ctx context.Context) GetManagementZonesValueArrayOutput {
	return o
}

func (o GetManagementZonesValueArrayOutput) Index(i pulumi.IntInput) GetManagementZonesValueOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetManagementZonesValue {
		return vs[0].([]GetManagementZonesValue)[vs[1].(int)]
	}).(GetManagementZonesValueOutput)
}

type GetRemoteEnvironmentsRemoteEnvironment struct {
	Name         string `pulumi:"name"`
	NetworkScope string `pulumi:"networkScope"`
	Token        string `pulumi:"token"`
	Uri          string `pulumi:"uri"`
}

// GetRemoteEnvironmentsRemoteEnvironmentInput is an input type that accepts GetRemoteEnvironmentsRemoteEnvironmentArgs and GetRemoteEnvironmentsRemoteEnvironmentOutput values.
// You can construct a concrete instance of `GetRemoteEnvironmentsRemoteEnvironmentInput` via:
//
//	GetRemoteEnvironmentsRemoteEnvironmentArgs{...}
type GetRemoteEnvironmentsRemoteEnvironmentInput interface {
	pulumi.Input

	ToGetRemoteEnvironmentsRemoteEnvironmentOutput() GetRemoteEnvironmentsRemoteEnvironmentOutput
	ToGetRemoteEnvironmentsRemoteEnvironmentOutputWithContext(context.Context) GetRemoteEnvironmentsRemoteEnvironmentOutput
}

type GetRemoteEnvironmentsRemoteEnvironmentArgs struct {
	Name         pulumi.StringInput `pulumi:"name"`
	NetworkScope pulumi.StringInput `pulumi:"networkScope"`
	Token        pulumi.StringInput `pulumi:"token"`
	Uri          pulumi.StringInput `pulumi:"uri"`
}

func (GetRemoteEnvironmentsRemoteEnvironmentArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetRemoteEnvironmentsRemoteEnvironment)(nil)).Elem()
}

func (i GetRemoteEnvironmentsRemoteEnvironmentArgs) ToGetRemoteEnvironmentsRemoteEnvironmentOutput() GetRemoteEnvironmentsRemoteEnvironmentOutput {
	return i.ToGetRemoteEnvironmentsRemoteEnvironmentOutputWithContext(context.Background())
}

func (i GetRemoteEnvironmentsRemoteEnvironmentArgs) ToGetRemoteEnvironmentsRemoteEnvironmentOutputWithContext(ctx context.Context) GetRemoteEnvironmentsRemoteEnvironmentOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetRemoteEnvironmentsRemoteEnvironmentOutput)
}

// GetRemoteEnvironmentsRemoteEnvironmentArrayInput is an input type that accepts GetRemoteEnvironmentsRemoteEnvironmentArray and GetRemoteEnvironmentsRemoteEnvironmentArrayOutput values.
// You can construct a concrete instance of `GetRemoteEnvironmentsRemoteEnvironmentArrayInput` via:
//
//	GetRemoteEnvironmentsRemoteEnvironmentArray{ GetRemoteEnvironmentsRemoteEnvironmentArgs{...} }
type GetRemoteEnvironmentsRemoteEnvironmentArrayInput interface {
	pulumi.Input

	ToGetRemoteEnvironmentsRemoteEnvironmentArrayOutput() GetRemoteEnvironmentsRemoteEnvironmentArrayOutput
	ToGetRemoteEnvironmentsRemoteEnvironmentArrayOutputWithContext(context.Context) GetRemoteEnvironmentsRemoteEnvironmentArrayOutput
}

type GetRemoteEnvironmentsRemoteEnvironmentArray []GetRemoteEnvironmentsRemoteEnvironmentInput

func (GetRemoteEnvironmentsRemoteEnvironmentArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetRemoteEnvironmentsRemoteEnvironment)(nil)).Elem()
}

func (i GetRemoteEnvironmentsRemoteEnvironmentArray) ToGetRemoteEnvironmentsRemoteEnvironmentArrayOutput() GetRemoteEnvironmentsRemoteEnvironmentArrayOutput {
	return i.ToGetRemoteEnvironmentsRemoteEnvironmentArrayOutputWithContext(context.Background())
}

func (i GetRemoteEnvironmentsRemoteEnvironmentArray) ToGetRemoteEnvironmentsRemoteEnvironmentArrayOutputWithContext(ctx context.Context) GetRemoteEnvironmentsRemoteEnvironmentArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetRemoteEnvironmentsRemoteEnvironmentArrayOutput)
}

type GetRemoteEnvironmentsRemoteEnvironmentOutput struct{ *pulumi.OutputState }

func (GetRemoteEnvironmentsRemoteEnvironmentOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetRemoteEnvironmentsRemoteEnvironment)(nil)).Elem()
}

func (o GetRemoteEnvironmentsRemoteEnvironmentOutput) ToGetRemoteEnvironmentsRemoteEnvironmentOutput() GetRemoteEnvironmentsRemoteEnvironmentOutput {
	return o
}

func (o GetRemoteEnvironmentsRemoteEnvironmentOutput) ToGetRemoteEnvironmentsRemoteEnvironmentOutputWithContext(ctx context.Context) GetRemoteEnvironmentsRemoteEnvironmentOutput {
	return o
}

func (o GetRemoteEnvironmentsRemoteEnvironmentOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetRemoteEnvironmentsRemoteEnvironment) string { return v.Name }).(pulumi.StringOutput)
}

func (o GetRemoteEnvironmentsRemoteEnvironmentOutput) NetworkScope() pulumi.StringOutput {
	return o.ApplyT(func(v GetRemoteEnvironmentsRemoteEnvironment) string { return v.NetworkScope }).(pulumi.StringOutput)
}

func (o GetRemoteEnvironmentsRemoteEnvironmentOutput) Token() pulumi.StringOutput {
	return o.ApplyT(func(v GetRemoteEnvironmentsRemoteEnvironment) string { return v.Token }).(pulumi.StringOutput)
}

func (o GetRemoteEnvironmentsRemoteEnvironmentOutput) Uri() pulumi.StringOutput {
	return o.ApplyT(func(v GetRemoteEnvironmentsRemoteEnvironment) string { return v.Uri }).(pulumi.StringOutput)
}

type GetRemoteEnvironmentsRemoteEnvironmentArrayOutput struct{ *pulumi.OutputState }

func (GetRemoteEnvironmentsRemoteEnvironmentArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetRemoteEnvironmentsRemoteEnvironment)(nil)).Elem()
}

func (o GetRemoteEnvironmentsRemoteEnvironmentArrayOutput) ToGetRemoteEnvironmentsRemoteEnvironmentArrayOutput() GetRemoteEnvironmentsRemoteEnvironmentArrayOutput {
	return o
}

func (o GetRemoteEnvironmentsRemoteEnvironmentArrayOutput) ToGetRemoteEnvironmentsRemoteEnvironmentArrayOutputWithContext(ctx context.Context) GetRemoteEnvironmentsRemoteEnvironmentArrayOutput {
	return o
}

func (o GetRemoteEnvironmentsRemoteEnvironmentArrayOutput) Index(i pulumi.IntInput) GetRemoteEnvironmentsRemoteEnvironmentOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetRemoteEnvironmentsRemoteEnvironment {
		return vs[0].([]GetRemoteEnvironmentsRemoteEnvironment)[vs[1].(int)]
	}).(GetRemoteEnvironmentsRemoteEnvironmentOutput)
}

type GetSyntheticLocationsLocations struct {
	// The cloud provider where the location is hosted.
	CloudPlatform string   `pulumi:"cloudPlatform"`
	EntityId      *string  `pulumi:"entityId"`
	Ips           []string `pulumi:"ips"`
	Name          *string  `pulumi:"name"`
	Stage         string   `pulumi:"stage"`
	Status        string   `pulumi:"status"`
	Type          *string  `pulumi:"type"`
}

// GetSyntheticLocationsLocationsInput is an input type that accepts GetSyntheticLocationsLocationsArgs and GetSyntheticLocationsLocationsOutput values.
// You can construct a concrete instance of `GetSyntheticLocationsLocationsInput` via:
//
//	GetSyntheticLocationsLocationsArgs{...}
type GetSyntheticLocationsLocationsInput interface {
	pulumi.Input

	ToGetSyntheticLocationsLocationsOutput() GetSyntheticLocationsLocationsOutput
	ToGetSyntheticLocationsLocationsOutputWithContext(context.Context) GetSyntheticLocationsLocationsOutput
}

type GetSyntheticLocationsLocationsArgs struct {
	// The cloud provider where the location is hosted.
	CloudPlatform pulumi.StringInput      `pulumi:"cloudPlatform"`
	EntityId      pulumi.StringPtrInput   `pulumi:"entityId"`
	Ips           pulumi.StringArrayInput `pulumi:"ips"`
	Name          pulumi.StringPtrInput   `pulumi:"name"`
	Stage         pulumi.StringInput      `pulumi:"stage"`
	Status        pulumi.StringInput      `pulumi:"status"`
	Type          pulumi.StringPtrInput   `pulumi:"type"`
}

func (GetSyntheticLocationsLocationsArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetSyntheticLocationsLocations)(nil)).Elem()
}

func (i GetSyntheticLocationsLocationsArgs) ToGetSyntheticLocationsLocationsOutput() GetSyntheticLocationsLocationsOutput {
	return i.ToGetSyntheticLocationsLocationsOutputWithContext(context.Background())
}

func (i GetSyntheticLocationsLocationsArgs) ToGetSyntheticLocationsLocationsOutputWithContext(ctx context.Context) GetSyntheticLocationsLocationsOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetSyntheticLocationsLocationsOutput)
}

func (i GetSyntheticLocationsLocationsArgs) ToGetSyntheticLocationsLocationsPtrOutput() GetSyntheticLocationsLocationsPtrOutput {
	return i.ToGetSyntheticLocationsLocationsPtrOutputWithContext(context.Background())
}

func (i GetSyntheticLocationsLocationsArgs) ToGetSyntheticLocationsLocationsPtrOutputWithContext(ctx context.Context) GetSyntheticLocationsLocationsPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetSyntheticLocationsLocationsOutput).ToGetSyntheticLocationsLocationsPtrOutputWithContext(ctx)
}

// GetSyntheticLocationsLocationsPtrInput is an input type that accepts GetSyntheticLocationsLocationsArgs, GetSyntheticLocationsLocationsPtr and GetSyntheticLocationsLocationsPtrOutput values.
// You can construct a concrete instance of `GetSyntheticLocationsLocationsPtrInput` via:
//
//	        GetSyntheticLocationsLocationsArgs{...}
//
//	or:
//
//	        nil
type GetSyntheticLocationsLocationsPtrInput interface {
	pulumi.Input

	ToGetSyntheticLocationsLocationsPtrOutput() GetSyntheticLocationsLocationsPtrOutput
	ToGetSyntheticLocationsLocationsPtrOutputWithContext(context.Context) GetSyntheticLocationsLocationsPtrOutput
}

type getSyntheticLocationsLocationsPtrType GetSyntheticLocationsLocationsArgs

func GetSyntheticLocationsLocationsPtr(v *GetSyntheticLocationsLocationsArgs) GetSyntheticLocationsLocationsPtrInput {
	return (*getSyntheticLocationsLocationsPtrType)(v)
}

func (*getSyntheticLocationsLocationsPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**GetSyntheticLocationsLocations)(nil)).Elem()
}

func (i *getSyntheticLocationsLocationsPtrType) ToGetSyntheticLocationsLocationsPtrOutput() GetSyntheticLocationsLocationsPtrOutput {
	return i.ToGetSyntheticLocationsLocationsPtrOutputWithContext(context.Background())
}

func (i *getSyntheticLocationsLocationsPtrType) ToGetSyntheticLocationsLocationsPtrOutputWithContext(ctx context.Context) GetSyntheticLocationsLocationsPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetSyntheticLocationsLocationsPtrOutput)
}

type GetSyntheticLocationsLocationsOutput struct{ *pulumi.OutputState }

func (GetSyntheticLocationsLocationsOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetSyntheticLocationsLocations)(nil)).Elem()
}

func (o GetSyntheticLocationsLocationsOutput) ToGetSyntheticLocationsLocationsOutput() GetSyntheticLocationsLocationsOutput {
	return o
}

func (o GetSyntheticLocationsLocationsOutput) ToGetSyntheticLocationsLocationsOutputWithContext(ctx context.Context) GetSyntheticLocationsLocationsOutput {
	return o
}

func (o GetSyntheticLocationsLocationsOutput) ToGetSyntheticLocationsLocationsPtrOutput() GetSyntheticLocationsLocationsPtrOutput {
	return o.ToGetSyntheticLocationsLocationsPtrOutputWithContext(context.Background())
}

func (o GetSyntheticLocationsLocationsOutput) ToGetSyntheticLocationsLocationsPtrOutputWithContext(ctx context.Context) GetSyntheticLocationsLocationsPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v GetSyntheticLocationsLocations) *GetSyntheticLocationsLocations {
		return &v
	}).(GetSyntheticLocationsLocationsPtrOutput)
}

// The cloud provider where the location is hosted.
func (o GetSyntheticLocationsLocationsOutput) CloudPlatform() pulumi.StringOutput {
	return o.ApplyT(func(v GetSyntheticLocationsLocations) string { return v.CloudPlatform }).(pulumi.StringOutput)
}

func (o GetSyntheticLocationsLocationsOutput) EntityId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetSyntheticLocationsLocations) *string { return v.EntityId }).(pulumi.StringPtrOutput)
}

func (o GetSyntheticLocationsLocationsOutput) Ips() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetSyntheticLocationsLocations) []string { return v.Ips }).(pulumi.StringArrayOutput)
}

func (o GetSyntheticLocationsLocationsOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetSyntheticLocationsLocations) *string { return v.Name }).(pulumi.StringPtrOutput)
}

func (o GetSyntheticLocationsLocationsOutput) Stage() pulumi.StringOutput {
	return o.ApplyT(func(v GetSyntheticLocationsLocations) string { return v.Stage }).(pulumi.StringOutput)
}

func (o GetSyntheticLocationsLocationsOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v GetSyntheticLocationsLocations) string { return v.Status }).(pulumi.StringOutput)
}

func (o GetSyntheticLocationsLocationsOutput) Type() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetSyntheticLocationsLocations) *string { return v.Type }).(pulumi.StringPtrOutput)
}

type GetSyntheticLocationsLocationsPtrOutput struct{ *pulumi.OutputState }

func (GetSyntheticLocationsLocationsPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**GetSyntheticLocationsLocations)(nil)).Elem()
}

func (o GetSyntheticLocationsLocationsPtrOutput) ToGetSyntheticLocationsLocationsPtrOutput() GetSyntheticLocationsLocationsPtrOutput {
	return o
}

func (o GetSyntheticLocationsLocationsPtrOutput) ToGetSyntheticLocationsLocationsPtrOutputWithContext(ctx context.Context) GetSyntheticLocationsLocationsPtrOutput {
	return o
}

func (o GetSyntheticLocationsLocationsPtrOutput) Elem() GetSyntheticLocationsLocationsOutput {
	return o.ApplyT(func(v *GetSyntheticLocationsLocations) GetSyntheticLocationsLocations {
		if v != nil {
			return *v
		}
		var ret GetSyntheticLocationsLocations
		return ret
	}).(GetSyntheticLocationsLocationsOutput)
}

// The cloud provider where the location is hosted.
func (o GetSyntheticLocationsLocationsPtrOutput) CloudPlatform() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *GetSyntheticLocationsLocations) *string {
		if v == nil {
			return nil
		}
		return &v.CloudPlatform
	}).(pulumi.StringPtrOutput)
}

func (o GetSyntheticLocationsLocationsPtrOutput) EntityId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *GetSyntheticLocationsLocations) *string {
		if v == nil {
			return nil
		}
		return v.EntityId
	}).(pulumi.StringPtrOutput)
}

func (o GetSyntheticLocationsLocationsPtrOutput) Ips() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *GetSyntheticLocationsLocations) []string {
		if v == nil {
			return nil
		}
		return v.Ips
	}).(pulumi.StringArrayOutput)
}

func (o GetSyntheticLocationsLocationsPtrOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *GetSyntheticLocationsLocations) *string {
		if v == nil {
			return nil
		}
		return v.Name
	}).(pulumi.StringPtrOutput)
}

func (o GetSyntheticLocationsLocationsPtrOutput) Stage() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *GetSyntheticLocationsLocations) *string {
		if v == nil {
			return nil
		}
		return &v.Stage
	}).(pulumi.StringPtrOutput)
}

func (o GetSyntheticLocationsLocationsPtrOutput) Status() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *GetSyntheticLocationsLocations) *string {
		if v == nil {
			return nil
		}
		return &v.Status
	}).(pulumi.StringPtrOutput)
}

func (o GetSyntheticLocationsLocationsPtrOutput) Type() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *GetSyntheticLocationsLocations) *string {
		if v == nil {
			return nil
		}
		return v.Type
	}).(pulumi.StringPtrOutput)
}

type GetSyntheticNodesNode struct {
	ActiveGateVersion string   `pulumi:"activeGateVersion"`
	AutoUpdate        bool     `pulumi:"autoUpdate"`
	BrowserMonitors   bool     `pulumi:"browserMonitors"`
	HealthCheckStatus string   `pulumi:"healthCheckStatus"`
	Hostname          string   `pulumi:"hostname"`
	Id                string   `pulumi:"id"`
	Ips               []string `pulumi:"ips"`
	OneAgentRouting   bool     `pulumi:"oneAgentRouting"`
	OperatingSystem   string   `pulumi:"operatingSystem"`
	PlayerVersion     string   `pulumi:"playerVersion"`
	Status            string   `pulumi:"status"`
	Version           string   `pulumi:"version"`
}

// GetSyntheticNodesNodeInput is an input type that accepts GetSyntheticNodesNodeArgs and GetSyntheticNodesNodeOutput values.
// You can construct a concrete instance of `GetSyntheticNodesNodeInput` via:
//
//	GetSyntheticNodesNodeArgs{...}
type GetSyntheticNodesNodeInput interface {
	pulumi.Input

	ToGetSyntheticNodesNodeOutput() GetSyntheticNodesNodeOutput
	ToGetSyntheticNodesNodeOutputWithContext(context.Context) GetSyntheticNodesNodeOutput
}

type GetSyntheticNodesNodeArgs struct {
	ActiveGateVersion pulumi.StringInput      `pulumi:"activeGateVersion"`
	AutoUpdate        pulumi.BoolInput        `pulumi:"autoUpdate"`
	BrowserMonitors   pulumi.BoolInput        `pulumi:"browserMonitors"`
	HealthCheckStatus pulumi.StringInput      `pulumi:"healthCheckStatus"`
	Hostname          pulumi.StringInput      `pulumi:"hostname"`
	Id                pulumi.StringInput      `pulumi:"id"`
	Ips               pulumi.StringArrayInput `pulumi:"ips"`
	OneAgentRouting   pulumi.BoolInput        `pulumi:"oneAgentRouting"`
	OperatingSystem   pulumi.StringInput      `pulumi:"operatingSystem"`
	PlayerVersion     pulumi.StringInput      `pulumi:"playerVersion"`
	Status            pulumi.StringInput      `pulumi:"status"`
	Version           pulumi.StringInput      `pulumi:"version"`
}

func (GetSyntheticNodesNodeArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetSyntheticNodesNode)(nil)).Elem()
}

func (i GetSyntheticNodesNodeArgs) ToGetSyntheticNodesNodeOutput() GetSyntheticNodesNodeOutput {
	return i.ToGetSyntheticNodesNodeOutputWithContext(context.Background())
}

func (i GetSyntheticNodesNodeArgs) ToGetSyntheticNodesNodeOutputWithContext(ctx context.Context) GetSyntheticNodesNodeOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetSyntheticNodesNodeOutput)
}

// GetSyntheticNodesNodeArrayInput is an input type that accepts GetSyntheticNodesNodeArray and GetSyntheticNodesNodeArrayOutput values.
// You can construct a concrete instance of `GetSyntheticNodesNodeArrayInput` via:
//
//	GetSyntheticNodesNodeArray{ GetSyntheticNodesNodeArgs{...} }
type GetSyntheticNodesNodeArrayInput interface {
	pulumi.Input

	ToGetSyntheticNodesNodeArrayOutput() GetSyntheticNodesNodeArrayOutput
	ToGetSyntheticNodesNodeArrayOutputWithContext(context.Context) GetSyntheticNodesNodeArrayOutput
}

type GetSyntheticNodesNodeArray []GetSyntheticNodesNodeInput

func (GetSyntheticNodesNodeArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetSyntheticNodesNode)(nil)).Elem()
}

func (i GetSyntheticNodesNodeArray) ToGetSyntheticNodesNodeArrayOutput() GetSyntheticNodesNodeArrayOutput {
	return i.ToGetSyntheticNodesNodeArrayOutputWithContext(context.Background())
}

func (i GetSyntheticNodesNodeArray) ToGetSyntheticNodesNodeArrayOutputWithContext(ctx context.Context) GetSyntheticNodesNodeArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetSyntheticNodesNodeArrayOutput)
}

type GetSyntheticNodesNodeOutput struct{ *pulumi.OutputState }

func (GetSyntheticNodesNodeOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetSyntheticNodesNode)(nil)).Elem()
}

func (o GetSyntheticNodesNodeOutput) ToGetSyntheticNodesNodeOutput() GetSyntheticNodesNodeOutput {
	return o
}

func (o GetSyntheticNodesNodeOutput) ToGetSyntheticNodesNodeOutputWithContext(ctx context.Context) GetSyntheticNodesNodeOutput {
	return o
}

func (o GetSyntheticNodesNodeOutput) ActiveGateVersion() pulumi.StringOutput {
	return o.ApplyT(func(v GetSyntheticNodesNode) string { return v.ActiveGateVersion }).(pulumi.StringOutput)
}

func (o GetSyntheticNodesNodeOutput) AutoUpdate() pulumi.BoolOutput {
	return o.ApplyT(func(v GetSyntheticNodesNode) bool { return v.AutoUpdate }).(pulumi.BoolOutput)
}

func (o GetSyntheticNodesNodeOutput) BrowserMonitors() pulumi.BoolOutput {
	return o.ApplyT(func(v GetSyntheticNodesNode) bool { return v.BrowserMonitors }).(pulumi.BoolOutput)
}

func (o GetSyntheticNodesNodeOutput) HealthCheckStatus() pulumi.StringOutput {
	return o.ApplyT(func(v GetSyntheticNodesNode) string { return v.HealthCheckStatus }).(pulumi.StringOutput)
}

func (o GetSyntheticNodesNodeOutput) Hostname() pulumi.StringOutput {
	return o.ApplyT(func(v GetSyntheticNodesNode) string { return v.Hostname }).(pulumi.StringOutput)
}

func (o GetSyntheticNodesNodeOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetSyntheticNodesNode) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetSyntheticNodesNodeOutput) Ips() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetSyntheticNodesNode) []string { return v.Ips }).(pulumi.StringArrayOutput)
}

func (o GetSyntheticNodesNodeOutput) OneAgentRouting() pulumi.BoolOutput {
	return o.ApplyT(func(v GetSyntheticNodesNode) bool { return v.OneAgentRouting }).(pulumi.BoolOutput)
}

func (o GetSyntheticNodesNodeOutput) OperatingSystem() pulumi.StringOutput {
	return o.ApplyT(func(v GetSyntheticNodesNode) string { return v.OperatingSystem }).(pulumi.StringOutput)
}

func (o GetSyntheticNodesNodeOutput) PlayerVersion() pulumi.StringOutput {
	return o.ApplyT(func(v GetSyntheticNodesNode) string { return v.PlayerVersion }).(pulumi.StringOutput)
}

func (o GetSyntheticNodesNodeOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v GetSyntheticNodesNode) string { return v.Status }).(pulumi.StringOutput)
}

func (o GetSyntheticNodesNodeOutput) Version() pulumi.StringOutput {
	return o.ApplyT(func(v GetSyntheticNodesNode) string { return v.Version }).(pulumi.StringOutput)
}

type GetSyntheticNodesNodeArrayOutput struct{ *pulumi.OutputState }

func (GetSyntheticNodesNodeArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetSyntheticNodesNode)(nil)).Elem()
}

func (o GetSyntheticNodesNodeArrayOutput) ToGetSyntheticNodesNodeArrayOutput() GetSyntheticNodesNodeArrayOutput {
	return o
}

func (o GetSyntheticNodesNodeArrayOutput) ToGetSyntheticNodesNodeArrayOutputWithContext(ctx context.Context) GetSyntheticNodesNodeArrayOutput {
	return o
}

func (o GetSyntheticNodesNodeArrayOutput) Index(i pulumi.IntInput) GetSyntheticNodesNodeOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetSyntheticNodesNode {
		return vs[0].([]GetSyntheticNodesNode)[vs[1].(int)]
	}).(GetSyntheticNodesNodeOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*GetDocumentsValueInput)(nil)).Elem(), GetDocumentsValueArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetDocumentsValueArrayInput)(nil)).Elem(), GetDocumentsValueArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetEntitiesEntityInput)(nil)).Elem(), GetEntitiesEntityArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetEntitiesEntityArrayInput)(nil)).Elem(), GetEntitiesEntityArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetEntitiesEntityTagInput)(nil)).Elem(), GetEntitiesEntityTagArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetEntitiesEntityTagArrayInput)(nil)).Elem(), GetEntitiesEntityTagArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetEntitiesEntityTagTagInput)(nil)).Elem(), GetEntitiesEntityTagTagArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetEntitiesEntityTagTagArrayInput)(nil)).Elem(), GetEntitiesEntityTagTagArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetHubItemsItemInput)(nil)).Elem(), GetHubItemsItemArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetHubItemsItemArrayInput)(nil)).Elem(), GetHubItemsItemArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetManagementZonesValueInput)(nil)).Elem(), GetManagementZonesValueArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetManagementZonesValueArrayInput)(nil)).Elem(), GetManagementZonesValueArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetRemoteEnvironmentsRemoteEnvironmentInput)(nil)).Elem(), GetRemoteEnvironmentsRemoteEnvironmentArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetRemoteEnvironmentsRemoteEnvironmentArrayInput)(nil)).Elem(), GetRemoteEnvironmentsRemoteEnvironmentArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetSyntheticLocationsLocationsInput)(nil)).Elem(), GetSyntheticLocationsLocationsArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetSyntheticLocationsLocationsPtrInput)(nil)).Elem(), GetSyntheticLocationsLocationsArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetSyntheticNodesNodeInput)(nil)).Elem(), GetSyntheticNodesNodeArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetSyntheticNodesNodeArrayInput)(nil)).Elem(), GetSyntheticNodesNodeArray{})
	pulumi.RegisterOutputType(GetDocumentsValueOutput{})
	pulumi.RegisterOutputType(GetDocumentsValueArrayOutput{})
	pulumi.RegisterOutputType(GetEntitiesEntityOutput{})
	pulumi.RegisterOutputType(GetEntitiesEntityArrayOutput{})
	pulumi.RegisterOutputType(GetEntitiesEntityTagOutput{})
	pulumi.RegisterOutputType(GetEntitiesEntityTagArrayOutput{})
	pulumi.RegisterOutputType(GetEntitiesEntityTagTagOutput{})
	pulumi.RegisterOutputType(GetEntitiesEntityTagTagArrayOutput{})
	pulumi.RegisterOutputType(GetHubItemsItemOutput{})
	pulumi.RegisterOutputType(GetHubItemsItemArrayOutput{})
	pulumi.RegisterOutputType(GetManagementZonesValueOutput{})
	pulumi.RegisterOutputType(GetManagementZonesValueArrayOutput{})
	pulumi.RegisterOutputType(GetRemoteEnvironmentsRemoteEnvironmentOutput{})
	pulumi.RegisterOutputType(GetRemoteEnvironmentsRemoteEnvironmentArrayOutput{})
	pulumi.RegisterOutputType(GetSyntheticLocationsLocationsOutput{})
	pulumi.RegisterOutputType(GetSyntheticLocationsLocationsPtrOutput{})
	pulumi.RegisterOutputType(GetSyntheticNodesNodeOutput{})
	pulumi.RegisterOutputType(GetSyntheticNodesNodeArrayOutput{})
}
