// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Dynatrace.Inputs
{

    public sealed class ApplicationErrorRulesHttpErrorsRuleArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Capture (`true`) or ignore (`false`) the error
        /// </summary>
        [Input("capture")]
        public Input<bool>? Capture { get; set; }

        /// <summary>
        /// If `true`, match by errors that have CSP Rule violations
        /// </summary>
        [Input("considerBlockedRequests")]
        public Input<bool>? ConsiderBlockedRequests { get; set; }

        /// <summary>
        /// Include (`true`) or exclude (`false`) the error in Davis AI [problem detection and analysis](https://dt-url.net/a963kd2)
        /// </summary>
        [Input("considerForAi")]
        public Input<bool>? ConsiderForAi { get; set; }

        /// <summary>
        /// If `true`, match by errors that have unknown HTTP status code
        /// </summary>
        [Input("considerUnknownErrorCode")]
        public Input<bool>? ConsiderUnknownErrorCode { get; set; }

        /// <summary>
        /// The HTTP status code or status code range to match by.
        /// </summary>
        [Input("errorCodes")]
        public Input<string>? ErrorCodes { get; set; }

        [Input("filter")]
        public Input<string>? Filter { get; set; }

        [Input("filterByUrl")]
        public Input<bool>? FilterByUrl { get; set; }

        /// <summary>
        /// Include (`true`) or exclude (`false`) the error in Apdex calculation
        /// </summary>
        [Input("impactApdex")]
        public Input<bool>? ImpactApdex { get; set; }

        [Input("url")]
        public Input<string>? Url { get; set; }

        public ApplicationErrorRulesHttpErrorsRuleArgs()
        {
        }
        public static new ApplicationErrorRulesHttpErrorsRuleArgs Empty => new ApplicationErrorRulesHttpErrorsRuleArgs();
    }
}
