// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Dynatrace.Inputs
{

    public sealed class AppsecNotificationAttackCandidateBasedJiraPayloadGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("description", required: true)]
        public Input<string> Description { get; set; } = null!;

        [Input("summary", required: true)]
        public Input<string> Summary { get; set; } = null!;

        public AppsecNotificationAttackCandidateBasedJiraPayloadGetArgs()
        {
        }
        public static new AppsecNotificationAttackCandidateBasedJiraPayloadGetArgs Empty => new AppsecNotificationAttackCandidateBasedJiraPayloadGetArgs();
    }
}
