// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Dynatrace.Inputs
{

    public sealed class AppsecNotificationAttackCandidateBasedWebhookPayloadGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("payload", required: true)]
        public Input<string> Payload { get; set; } = null!;

        public AppsecNotificationAttackCandidateBasedWebhookPayloadGetArgs()
        {
        }
        public static new AppsecNotificationAttackCandidateBasedWebhookPayloadGetArgs Empty => new AppsecNotificationAttackCandidateBasedWebhookPayloadGetArgs();
    }
}
