// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Dynatrace.Inputs
{

    public sealed class AutomationWorkflowTriggerScheduleFilterParametersGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Specifies a maximum number of times that a task can be repeated in case it fails on execution. You can specify either a number between 1 and 99 here or use an expression (`{{}}`). Default: 1
        /// </summary>
        [Input("count")]
        public Input<int>? Count { get; set; }

        /// <summary>
        /// If specified, the schedule won't trigger executions before the given date
        /// </summary>
        [Input("earliestStart")]
        public Input<string>? EarliestStart { get; set; }

        /// <summary>
        /// If specified, the schedule won't trigger executions before the given time
        /// </summary>
        [Input("earliestStartTime")]
        public Input<string>? EarliestStartTime { get; set; }

        [Input("excludeDates")]
        private InputList<string>? _excludeDates;

        /// <summary>
        /// If specified, the schedule won't trigger exeuctions on the given dates
        /// </summary>
        public InputList<string> ExcludeDates
        {
            get => _excludeDates ?? (_excludeDates = new InputList<string>());
            set => _excludeDates = value;
        }

        [Input("includeDates")]
        private InputList<string>? _includeDates;

        /// <summary>
        /// If specified, the schedule will trigger executions on the given dates, even if the main configuration prohibits it
        /// </summary>
        public InputList<string> IncludeDates
        {
            get => _includeDates ?? (_includeDates = new InputList<string>());
            set => _includeDates = value;
        }

        /// <summary>
        /// If specified, the schedule won't trigger executions after the given date
        /// </summary>
        [Input("until")]
        public Input<string>? Until { get; set; }

        public AutomationWorkflowTriggerScheduleFilterParametersGetArgs()
        {
        }
        public static new AutomationWorkflowTriggerScheduleFilterParametersGetArgs Empty => new AutomationWorkflowTriggerScheduleFilterParametersGetArgs();
    }
}
