// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Dynatrace.Inputs
{

    public sealed class BrowserMonitorAnomalyDetectionOutageHandlingArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// (Field has overlap with `dynatrace.BrowserMonitorOutage` and `dynatrace.HttpMonitorOutage`) When enabled (`true`), generate a problem and send an alert when the monitor is unavailable at all configured locations
        /// </summary>
        [Input("globalOutage")]
        public Input<bool>? GlobalOutage { get; set; }

        [Input("globalOutagePolicies")]
        private InputList<Inputs.BrowserMonitorAnomalyDetectionOutageHandlingGlobalOutagePolicyArgs>? _globalOutagePolicies;

        /// <summary>
        /// (Field has overlap with `dynatrace.BrowserMonitorOutage` and `dynatrace.HttpMonitorOutage`) Global outage handling configuration.
        /// </summary>
        public InputList<Inputs.BrowserMonitorAnomalyDetectionOutageHandlingGlobalOutagePolicyArgs> GlobalOutagePolicies
        {
            get => _globalOutagePolicies ?? (_globalOutagePolicies = new InputList<Inputs.BrowserMonitorAnomalyDetectionOutageHandlingGlobalOutagePolicyArgs>());
            set => _globalOutagePolicies = value;
        }

        [Input("localOutage")]
        public Input<bool>? LocalOutage { get; set; }

        [Input("localOutagePolicies")]
        private InputList<Inputs.BrowserMonitorAnomalyDetectionOutageHandlingLocalOutagePolicyArgs>? _localOutagePolicies;
        public InputList<Inputs.BrowserMonitorAnomalyDetectionOutageHandlingLocalOutagePolicyArgs> LocalOutagePolicies
        {
            get => _localOutagePolicies ?? (_localOutagePolicies = new InputList<Inputs.BrowserMonitorAnomalyDetectionOutageHandlingLocalOutagePolicyArgs>());
            set => _localOutagePolicies = value;
        }

        [Input("retryOnError")]
        public Input<bool>? RetryOnError { get; set; }

        public BrowserMonitorAnomalyDetectionOutageHandlingArgs()
        {
        }
        public static new BrowserMonitorAnomalyDetectionOutageHandlingArgs Empty => new BrowserMonitorAnomalyDetectionOutageHandlingArgs();
    }
}
