// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Dynatrace.Inputs
{

    public sealed class DashboardTileFilterConfigGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Configuration of a custom chart
        /// </summary>
        [Input("chartConfig")]
        public Input<Inputs.DashboardTileFilterConfigChartConfigGetArgs>? ChartConfig { get; set; }

        /// <summary>
        /// The name of the tile, set by user
        /// </summary>
        [Input("customName", required: true)]
        public Input<string> CustomName { get; set; } = null!;

        /// <summary>
        /// The default name of the tile
        /// </summary>
        [Input("defaultName", required: true)]
        public Input<string> DefaultName { get; set; } = null!;

        /// <summary>
        /// A set of all possible global dashboard filters that can be applied to a dashboard
        /// </summary>
        [Input("filters")]
        public Input<Inputs.DashboardTileFilterConfigFiltersGetArgs>? Filters { get; set; }

        /// <summary>
        /// The visualization of the timeseries chart. Possible values are `AREA`, `BAR` and `LINE`.
        /// </summary>
        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        /// <summary>
        /// allows for configuring properties that are not explicitly supported by the current version of this provider
        /// </summary>
        [Input("unknowns")]
        public Input<string>? Unknowns { get; set; }

        public DashboardTileFilterConfigGetArgs()
        {
        }
        public static new DashboardTileFilterConfigGetArgs Empty => new DashboardTileFilterConfigGetArgs();
    }
}
