// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Dynatrace.Inputs
{

    public sealed class DataPrivacyUserTrackingGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("persistentCookieEnabled", required: true)]
        public Input<bool> PersistentCookieEnabled { get; set; } = null!;

        public DataPrivacyUserTrackingGetArgs()
        {
        }
        public static new DataPrivacyUserTrackingGetArgs Empty => new DataPrivacyUserTrackingGetArgs();
    }
}
