// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Dynatrace.Inputs
{

    public sealed class DataPrivacyMaskingGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("ipAddressMasking")]
        public Input<string>? IpAddressMasking { get; set; }

        [Input("ipAddressMaskingEnabled")]
        public Input<bool>? IpAddressMaskingEnabled { get; set; }

        [Input("personalDataUriMaskingEnabled", required: true)]
        public Input<bool> PersonalDataUriMaskingEnabled { get; set; } = null!;

        [Input("userActionMaskingEnabled", required: true)]
        public Input<bool> UserActionMaskingEnabled { get; set; } = null!;

        public DataPrivacyMaskingGetArgs()
        {
        }
        public static new DataPrivacyMaskingGetArgs Empty => new DataPrivacyMaskingGetArgs();
    }
}
