// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Dynatrace.Inputs
{

    public sealed class DataPrivacyDataCollectionArgs : global::Pulumi.ResourceArgs
    {
        [Input("optInModeEnabled", required: true)]
        public Input<bool> OptInModeEnabled { get; set; } = null!;

        public DataPrivacyDataCollectionArgs()
        {
        }
        public static new DataPrivacyDataCollectionArgs Empty => new DataPrivacyDataCollectionArgs();
    }
}
