// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Dynatrace.Inputs
{

    public sealed class EnvironmentStorageLimitsArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Log Monitoring consumption and quota information on environment level. Not set (and not editable) if Log monitoring is not enabled. Not set (and not editable) if Log monitoring is migrated to Davis data on license level
        /// </summary>
        [Input("logs")]
        public Input<int>? Logs { get; set; }

        /// <summary>
        /// Session replay storage usage and limit information on environment level in bytes. 0 for unlimited.
        /// </summary>
        [Input("sessionReplay")]
        public Input<int>? SessionReplay { get; set; }

        /// <summary>
        /// Session replay storage usage and limit information on environment level in bytes. 0 for unlimited.
        /// </summary>
        [Input("symbolFiles")]
        public Input<int>? SymbolFiles { get; set; }

        /// <summary>
        /// Transaction storage usage and limit information on environment level in bytes. 0 for unlimited.
        /// </summary>
        [Input("transactions")]
        public Input<int>? Transactions { get; set; }

        public EnvironmentStorageLimitsArgs()
        {
        }
        public static new EnvironmentStorageLimitsArgs Empty => new EnvironmentStorageLimitsArgs();
    }
}
