// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Dynatrace.Inputs
{

    public sealed class GenericTypesRulesRuleRequiredDimensionsRequiredDimensionArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The attribute key is the unique name of the attribute.
        /// </summary>
        [Input("key", required: true)]
        public Input<string> Key { get; set; } = null!;

        /// <summary>
        /// A dimension value pattern which needs to exist in the ingest data to match this filter.
        /// </summary>
        [Input("valuePattern")]
        public Input<string>? ValuePattern { get; set; }

        public GenericTypesRulesRuleRequiredDimensionsRequiredDimensionArgs()
        {
        }
        public static new GenericTypesRulesRuleRequiredDimensionsRequiredDimensionArgs Empty => new GenericTypesRulesRuleRequiredDimensionsRequiredDimensionArgs();
    }
}
