// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Dynatrace.Inputs
{

    public sealed class GenericTypesRulesRuleGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("attributes")]
        public Input<Inputs.GenericTypesRulesRuleAttributesGetArgs>? Attributes { get; set; }

        [Input("iconPattern")]
        public Input<string>? IconPattern { get; set; }

        /// <summary>
        /// ID patterns are comprised of static text and placeholders referring to dimensions in the ingest data. An ID pattern **must** contain at least one placeholder to ensure that different entities will be created.. Take care that the pattern results in the same ID for the same entity. For example, using timestamp or counter-like dimensions as part of the ID would lead to the creation of new entities for each ingest data and is strongly discouraged!
        /// </summary>
        [Input("idPattern", required: true)]
        public Input<string> IdPattern { get; set; } = null!;

        [Input("instanceNamePattern")]
        public Input<string>? InstanceNamePattern { get; set; }

        [Input("requiredDimensions")]
        public Input<Inputs.GenericTypesRulesRuleRequiredDimensionsGetArgs>? RequiredDimensions { get; set; }

        [Input("role")]
        public Input<string>? Role { get; set; }

        [Input("sources", required: true)]
        public Input<Inputs.GenericTypesRulesRuleSourcesGetArgs> Sources { get; set; } = null!;

        public GenericTypesRulesRuleGetArgs()
        {
        }
        public static new GenericTypesRulesRuleGetArgs Empty => new GenericTypesRulesRuleGetArgs();
    }
}
