// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Dynatrace.Inputs
{

    public sealed class HostAnomaliesV2NetworkNetworkErrorsDetectionCustomThresholdsGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Alert if sent/received traffic utilization is higher than this threshold for the defined amount of samples
        /// </summary>
        [Input("errorsPercentage", required: true)]
        public Input<int> ErrorsPercentage { get; set; } = null!;

        /// <summary>
        /// no documentation available
        /// </summary>
        [Input("eventThresholds", required: true)]
        public Input<Inputs.HostAnomaliesV2NetworkNetworkErrorsDetectionCustomThresholdsEventThresholdsGetArgs> EventThresholds { get; set; } = null!;

        /// <summary>
        /// Total packets rate threshold
        /// </summary>
        [Input("totalPacketsRate", required: true)]
        public Input<int> TotalPacketsRate { get; set; } = null!;

        public HostAnomaliesV2NetworkNetworkErrorsDetectionCustomThresholdsGetArgs()
        {
        }
        public static new HostAnomaliesV2NetworkNetworkErrorsDetectionCustomThresholdsGetArgs Empty => new HostAnomaliesV2NetworkNetworkErrorsDetectionCustomThresholdsGetArgs();
    }
}
