// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Dynatrace.Inputs
{

    public sealed class HostAnomaliesV2HostHighGcActivityDetectionArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// no documentation available
        /// </summary>
        [Input("customThresholds")]
        public Input<Inputs.HostAnomaliesV2HostHighGcActivityDetectionCustomThresholdsArgs>? CustomThresholds { get; set; }

        /// <summary>
        /// Detection mode for CPU saturation
        /// </summary>
        [Input("detectionMode")]
        public Input<string>? DetectionMode { get; set; }

        /// <summary>
        /// Detect host or monitoring connection lost problems
        /// </summary>
        [Input("enabled", required: true)]
        public Input<bool> Enabled { get; set; } = null!;

        public HostAnomaliesV2HostHighGcActivityDetectionArgs()
        {
        }
        public static new HostAnomaliesV2HostHighGcActivityDetectionArgs Empty => new HostAnomaliesV2HostHighGcActivityDetectionArgs();
    }
}
