// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Dynatrace.Inputs
{

    public sealed class ProcessAvailabilityRulesRuleGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("condition")]
        public Input<string>? Condition { get; set; }

        [Input("hostMetadataCondition")]
        public Input<Inputs.ProcessAvailabilityRulesRuleHostMetadataConditionGetArgs>? HostMetadataCondition { get; set; }

        [Input("property")]
        public Input<string>? Property { get; set; }

        [Input("ruleType")]
        public Input<string>? RuleType { get; set; }

        public ProcessAvailabilityRulesRuleGetArgs()
        {
        }
        public static new ProcessAvailabilityRulesRuleGetArgs Empty => new ProcessAvailabilityRulesRuleGetArgs();
    }
}
