// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Dynatrace.Inputs
{

    public sealed class ProcessAvailabilityRulesRuleHostMetadataConditionArgs : global::Pulumi.ResourceArgs
    {
        [Input("metadataCondition", required: true)]
        public Input<string> MetadataCondition { get; set; } = null!;

        [Input("metadataKey", required: true)]
        public Input<string> MetadataKey { get; set; } = null!;

        public ProcessAvailabilityRulesRuleHostMetadataConditionArgs()
        {
        }
        public static new ProcessAvailabilityRulesRuleHostMetadataConditionArgs Empty => new ProcessAvailabilityRulesRuleHostMetadataConditionArgs();
    }
}
