// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Dynatrace.Inputs
{

    public sealed class SiteReliabilityGuardianVariablesVariableGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Value
        /// </summary>
        [Input("definition", required: true)]
        public Input<string> Definition { get; set; } = null!;

        /// <summary>
        /// Objective name
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        public SiteReliabilityGuardianVariablesVariableGetArgs()
        {
        }
        public static new SiteReliabilityGuardianVariablesVariableGetArgs Empty => new SiteReliabilityGuardianVariablesVariableGetArgs();
    }
}
