// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Dynatrace.Inputs
{

    public sealed class WebApplicationMonitoringSettingsAdvancedJavascriptTagSettingsGlobalEventCaptureSettingsArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Additional events to be captured globally as user input.
        /// </summary>
        [Input("additionalEventCapturedAsUserInput")]
        public Input<string>? AdditionalEventCapturedAsUserInput { get; set; }

        /// <summary>
        /// Change event handler enabled/disabled
        /// </summary>
        [Input("change")]
        public Input<bool>? Change { get; set; }

        /// <summary>
        /// Click event handler enabled/disabled
        /// </summary>
        [Input("click")]
        public Input<bool>? Click { get; set; }

        [Input("doubleclick")]
        public Input<bool>? Doubleclick { get; set; }

        [Input("keydown")]
        public Input<bool>? Keydown { get; set; }

        [Input("keyup")]
        public Input<bool>? Keyup { get; set; }

        [Input("mousedown")]
        public Input<bool>? Mousedown { get; set; }

        /// <summary>
        /// Mouseup event handler enabled/disabled
        /// </summary>
        [Input("mouseup")]
        public Input<bool>? Mouseup { get; set; }

        [Input("scroll")]
        public Input<bool>? Scroll { get; set; }

        /// <summary>
        /// TouchEnd enabled/disabled
        /// </summary>
        [Input("touchEnd")]
        public Input<bool>? TouchEnd { get; set; }

        /// <summary>
        /// TouchStart enabled/disabled
        /// </summary>
        [Input("touchStart")]
        public Input<bool>? TouchStart { get; set; }

        public WebApplicationMonitoringSettingsAdvancedJavascriptTagSettingsGlobalEventCaptureSettingsArgs()
        {
        }
        public static new WebApplicationMonitoringSettingsAdvancedJavascriptTagSettingsGlobalEventCaptureSettingsArgs Empty => new WebApplicationMonitoringSettingsAdvancedJavascriptTagSettingsGlobalEventCaptureSettingsArgs();
    }
}
