// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Dynatrace.Inputs
{

    public sealed class WebApplicationUserActionAndSessionPropertiesPropertyGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The aggregation type of the property.
        /// </summary>
        [Input("aggregation")]
        public Input<string>? Aggregation { get; set; }

        /// <summary>
        /// Cleanup rule expression of the userTag
        /// </summary>
        [Input("cleanupRule")]
        public Input<string>? CleanupRule { get; set; }

        [Input("displayName")]
        public Input<string>? DisplayName { get; set; }

        /// <summary>
        /// The ID of conversion goal.
        /// </summary>
        [Input("id", required: true)]
        public Input<int> Id { get; set; } = null!;

        /// <summary>
        /// Case insensitive naming
        /// </summary>
        [Input("ignoreCase")]
        public Input<bool>? IgnoreCase { get; set; }

        /// <summary>
        /// Key of the property
        /// </summary>
        [Input("key", required: true)]
        public Input<string> Key { get; set; } = null!;

        [Input("longStringLength")]
        public Input<int>? LongStringLength { get; set; }

        /// <summary>
        /// The ID of the metadata
        /// </summary>
        [Input("metadataId")]
        public Input<int>? MetadataId { get; set; }

        /// <summary>
        /// The origin of the property. Possible values are `JAVASCRIPT_API`, `META_DATA` and `SERVER_SIDE_REQUEST_ATTRIBUTE`.
        /// </summary>
        [Input("origin", required: true)]
        public Input<string> Origin { get; set; } = null!;

        /// <summary>
        /// The ID of the RrequestAttribute for the userTag
        /// </summary>
        [Input("serverSideRequestAttribute")]
        public Input<string>? ServerSideRequestAttribute { get; set; }

        [Input("storeAsSessionProperty")]
        public Input<bool>? StoreAsSessionProperty { get; set; }

        [Input("storeAsUserActionProperty")]
        public Input<bool>? StoreAsUserActionProperty { get; set; }

        /// <summary>
        /// The type of the action. Possible values are `Custom`, `Load` and `Xhr`.
        /// </summary>
        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        public WebApplicationUserActionAndSessionPropertiesPropertyGetArgs()
        {
        }
        public static new WebApplicationUserActionAndSessionPropertiesPropertyGetArgs Empty => new WebApplicationUserActionAndSessionPropertiesPropertyGetArgs();
    }
}
