// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Dynatrace.Inputs
{

    public sealed class WebApplicationConversionGoalsGoalGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Configuration of a destination-based conversion goal
        /// </summary>
        [Input("destination")]
        public Input<Inputs.WebApplicationConversionGoalsGoalDestinationGetArgs>? Destination { get; set; }

        /// <summary>
        /// The ID of conversion goal.
        /// </summary>
        [Input("id")]
        public Input<string>? Id { get; set; }

        /// <summary>
        /// The name of the conversion goal. Valid length within 1 and 50 characters.
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        /// <summary>
        /// The type of the action. Possible values are `Custom`, `Load` and `Xhr`.
        /// </summary>
        [Input("type")]
        public Input<string>? Type { get; set; }

        [Input("userAction")]
        public Input<Inputs.WebApplicationConversionGoalsGoalUserActionGetArgs>? UserAction { get; set; }

        [Input("visitDuration")]
        public Input<Inputs.WebApplicationConversionGoalsGoalVisitDurationGetArgs>? VisitDuration { get; set; }

        [Input("visitNumAction")]
        public Input<Inputs.WebApplicationConversionGoalsGoalVisitNumActionGetArgs>? VisitNumAction { get; set; }

        public WebApplicationConversionGoalsGoalGetArgs()
        {
        }
        public static new WebApplicationConversionGoalsGoalGetArgs Empty => new WebApplicationConversionGoalsGoalGetArgs();
    }
}
