// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Retrieve a list of all documents.
 */
export function getDocuments(args?: GetDocumentsArgs, opts?: pulumi.InvokeOptions): Promise<GetDocumentsResult> {
    args = args || {};

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("dynatrace:index/getDocuments:getDocuments", {
        "type": args.type,
    }, opts);
}

/**
 * A collection of arguments for invoking getDocuments.
 */
export interface GetDocumentsArgs {
    type?: string;
}

/**
 * A collection of values returned by getDocuments.
 */
export interface GetDocumentsResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * The type of documents to query for. Leave empty if you want to query for all kinds of documents. Possible values are `document` or `notebook`
     */
    readonly type?: string;
    readonly values: outputs.GetDocumentsValue[];
}
/**
 * Retrieve a list of all documents.
 */
export function getDocumentsOutput(args?: GetDocumentsOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetDocumentsResult> {
    return pulumi.output(args).apply((a: any) => getDocuments(a, opts))
}

/**
 * A collection of arguments for invoking getDocuments.
 */
export interface GetDocumentsOutputArgs {
    type?: pulumi.Input<string>;
}
